### PR TITLE
fix: improve desktop menu updates and feedback

### LINKED ISSUE #84: [Bug] Desktop menu actions and labels need cleanup
### What happened?

The macOS desktop menu has several user-visible problems reported during internal testing. PawWork > Check for Updates does not surface visible feedback on click; the updater code path exists (`packages/desktop-electron/src/main/index.ts:353` → `autoUpdater.checkForUpdates()`), so the root cause is likely missing UI feedback, release metadata, or an updater gate condition — not a missing wire. PawWork > Reload Webview uses stale wording now that the shell is Electron-based. The desktop menu is still mostly English even when the app is used in Chinese. Help > Share Feedback and Help > Report a Bug currently open the same generic GitHub issue creation page, so the two entries do not lead to distinct workflows.

### Steps to reproduce

1. Open PawWork on macOS.
2. Open the PawWork application menu and click Check for Updates, then inspect Reload Webview.
3. Inspect the rest of the desktop menu while using the Chinese product flow.
4. Open Help and click Share Feedback, then Report a Bug.

### What did you expect to happen?

Check for Updates should show visible feedback whether or not an update is available (dialog or status in the menu item). Reload Webview should use current Electron-era wording. The macOS menu should be localized for Chinese users where PawWork controls the labels. Share Feedback and Report a Bug should lead to distinct, appropriate destinations.

### PawWork version

v0.2.4

### OS version

macOS, exact version not captured in the internal report.

### Can you reproduce it again?

Yes, every time

### Screenshots, recordings, or extra context

Implementation pointer from local triage: `packages/desktop-electron/src/main/menu.ts` currently hardcodes English menu labels, while `packages/desktop-electron/src/renderer/i18n/{zh,en}.ts` already has some desktop menu translation keys. The updater wire itself is connected (`main/index.ts:353`), so first diagnose which of `menu-click handler → feedback surfacing → updater gate → release metadata` is actually swallowing the interaction before assuming a functional break.

### PR DESCRIPTION
**Pull request by Astro-Han**
## Summary

- Localize PawWork-controlled desktop menu labels and keep Electron-era wording.
- Add a Report a Problem flow that copies a diagnostic markdown report with active window context, recent logs, and session messages, while keeping Open GitHub Issue available.
- Enable the non-GitHub feedback path with a Feishu form URL injected through `PAWWORK_FEEDBACK_FORM_URL`.
- Make desktop update checks report visible results from menu, settings, and crash page paths.
- Preserve updater metadata across release finalization so macOS architectures do not clobber each other.

## Why

Fixes desktop menu cleanup and update feedback gaps from #84. Also gives users without GitHub accounts a lower-friction Feishu form based bug report path while preserving the GitHub issue entry for developer workflows.

This also addresses the real v0.2.5 release failure mode: the release published successfully, but `latest-mac.yml` ended up containing only `pawwork-mac-x64.zip`/`.dmg` and dropped the arm64 entries. The old workflow packaged each macOS architecture independently and did not run a final metadata merge/upload step. This PR adds that workflow step and hardens `finalize-latest-yml.ts` so existing, live, and current-run updater metadata are merged before `latest*.yml` is re-uploaded.

## Related Issue

Fixes #84

## How To Verify

```bash
cd packages/desktop-electron && bun test src/main/updater.test.ts src/main/menu-labels.test.ts src/main/menu.test.ts src/main/feedback.test.ts src/main/desktop-context-store.test.ts src/main/problem-report.test.ts src/main/updater-dialog-labels.test.ts src/renderer/i18n/index.test.ts scripts/release-metadata-contract.test.ts
cd packages/app && bun test src/utils/desktop-context.test.ts src/context/language.test.ts src/pages/error-update.test.ts
cd packages/opencode && bun test test/github/build-workflow.test.ts
cd packages/desktop-electron && bun run typecheck
cd packages/app && bun run typecheck
git diff --check origin/dev..HEAD
```

Manual/config checks:

- Confirmed v0.2.5 release assets exist, but current `latest-mac.yml` only includes x64 metadata, validating the release metadata clobbering path this PR fixes.
- Created and cleaned up the Feishu Base form `PawWork Problem Report` in the `CENO&纯刻用户服务` project knowledge space.
- Enabled form sharing and verified `shared=true`, `shared_limit=anyone_editable`.
- Set and read back GitHub repo variable `PAWWORK_FEEDBACK_FORM_URL`.

## Screenshots or Recordings

Not included. Changes are native menu/dialog flows plus release metadata behavior. The external Feishu form was created and configured separately, and its URL is supplied by repository variable at build time.

## Checklist

- [x] I linked the related issue, or stated why there is no issue
- [x] This PR has type, scope, and priority labels, or I requested maintainer labeling
- [x] I listed the relevant verification steps, including tests when behavior changed
- [x] I manually checked visible UI or copy changes when needed, with screenshots or recordings
- [x] I considered macOS and Windows impact for desktop, packaging, updater, signing, paths, shell, or permissions changes
- [x] I called out docs, release notes, dependencies, permissions, credentials, deletion behavior, or generated/local file changes when relevant
- [x] I am targeting `dev`, and my PR title and commit messages use Conventional Commits in English

## Summary by CodeRabbit

* **New Features**
  * "Report a Problem" menu action: collects diagnostics, builds/copies a problem report, and opens the feedback form.
  * Per-window desktop context syncing with renderer→main IPC and persisted per-window locale.

* **Improvements**
  * Richer updater UX: explicit statuses (busy/disabled/failed/ready), localized dialogs, install/dismiss flows, and version-aware merging of updater metadata.
  * Feedback form URL propagated to builds and honored at runtime; localized menu labels with persisted detection.

* **Tests**
  * Extensive new tests covering updater, menu, feedback, problem-report, and release metadata flows.

### CODE REVIEW

File: packages/desktop-electron/scripts/finalize-latest-yml.ts [hunk 1]
```diff
@@ -76,18 +77,77 @@ async function read(subdir: string, filename: string): Promise<LatestYml | undef
...
+  else parts.push(String(error))
+  const maybe = error as { stdout?: unknown; stderr?: unknown }
+  if (maybe.stderr) parts.push(String(maybe.stderr))
+  if (maybe.stdout) parts.push(String(maybe.stdout))
+  return parts.join("\n")
+}
+
+function isMissingAssetError(message: string) {
+  return /no assets to download|no matches found|could not find any assets/i.test(message)
+}
```
[the remark this answers is not in the document]
Comment (Astro-Han) [reply packages/desktop-electron/scripts/finalize-latest-yml.ts:119]: Leaving this unchanged. Treating release not found as a missing asset would hide wrong tags, missing releases, or release-creation failures. In this workflow the publish step is expected to create the release before finalizer runs; if the release itself is absent, the finalizer should fail visibly instead of silently merging against a snapshot.

**Review by Astro-Han — COMMENTED** [review]
Code review for new modules. Minor issues worth addressing for consistency and correctness.

File: packages/desktop-electron/src/main/desktop-context-store.ts [hunk 2]
```diff
@@ -0,0 +1,23 @@
+import type { DesktopContext } from "../preload/types"
+
+export function createDesktopContextStore(fallback: () => DesktopContext) {
+  const contexts = new Map<number, DesktopContext>()
+  let mostRecent: DesktopContext | undefined
+
+  return {
+    set(windowID: number, context: DesktopContext) {
+      contexts.delete(windowID)
+      contexts.set(windowID, context)
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/desktop-context-store.ts:11]: Calling `delete` then `set` is redundant. `Map.set` overwrites existing entries, so just `contexts.set(windowID, context)` suffices. The delete adds overhead.

File: packages/desktop-electron/src/main/menu-i18n.ts [hunk 3]
```diff
@@ -0,0 +1,14 @@
...
+  const raw = getStore("opencode.global.dat").get("language")
+  const stored = parseMenuLocale(raw)
+  // Keep an explicit stored locale, including English; otherwise detect from the OS locale.
+  if (raw) return stored
+  return detectSystemMenuLocale(systemLocale)
+}
+
+export function writeStoredMenuLocale(locale: MenuLocale) {
+  getStore("opencode.global.dat").set("language", JSON.stringify({ locale }))
+}
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/menu-i18n.ts:16]: `writeStoredMenuLocale` wraps locale as `{ locale }` but `parseMenuLocale` handles both raw strings and objects. This asymmetry risks format mismatches if another code path writes raw strings. Document expected format or unify.

File: packages/desktop-electron/src/main/problem-report.ts [hunk 4]
```diff
@@ -0,0 +1,172 @@
...
+
+function jsonBytes(value: unknown) {
+  return bytes(JSON.stringify(value) ?? "")
+}
+
+function markdown(payload: Payload) {
+  return [
+    "# PawWork Problem Report",
+    "",
+    "Paste this report into the feedback form after reviewing it.",
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/problem-report.ts:70]: `sessionInfo !== null` is always true since `sessionInfo` starts as `undefined` (ternary on line 41). Should check `sessionInfo !== undefined` or initialize as `null`.

File: packages/desktop-electron/src/main/problem-report.ts [hunk 5]
```diff
@@ -0,0 +1,172 @@
...
+}
+
+function withSessionInfo(sessionExport: SessionExport, info: unknown): SessionExport {
+  if (sessionExport.status !== "ok") return sessionExport
+  return { ...sessionExport, info }
+}
+
+function truncateString(value: string, limit: number) {
+  return value.length > limit ? value.slice(0, limit) : value
+}
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/problem-report.ts:130]: Regex `[\s\S]*?` stops at first fence. If JSON contains triple backticks in content, parsing breaks. Validate extracted JSON or use a safer approach.

File: packages/desktop-electron/src/main/menu.ts [hunk 6]
```diff
@@ -1,134 +1,27 @@
...
-          label: "Report a Bug",
-          click: () => shell.openExternal("https://github.com/Astro-Han/pawwork/issues/new"),
-        },
-      ],
+  const template = buildMenuTemplate({
+    deps: {
+      ...deps,
+      openExternal: (url) => {
+        void shell.openExternal(url).catch((error) => {
+          console.warn("[menu] failed to open external url", { url, error })
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/menu.ts]: Using console.warn is inconsistent with the project logger used elsewhere. Consider logger.warn for traceability.

File: packages/desktop-electron/src/main/index.ts [hunk 7]
```diff
@@ -68,11 +75,129 @@ let mainWindow: BrowserWindow | null = null
...
+    route: typeof value.route === "string" && value.route.length > 0 ? value.route : "/",
+    locale: value.locale === "zh" ? "zh" : "en",
+  }
+}
+
+const reportProblem = createFeedbackHandler({
+  feedbackUrl: FEEDBACK_FORM_URL,
+  context: currentDesktopContext,
+  confirm: async (context) => {
+    const labels = feedbackDialogLabels((context as DesktopContext | undefined)?.locale ?? menuLocale)
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/index.ts]: Type assertion could mask runtime errors. Use normalizeDesktopContext() or add explicit type checking.

File: packages/app/src/pages/session.tsx [hunk 8]
```diff
@@ -333,8 +334,54 @@ export default function Page() {
...
+        if (desktopContextRetryTimer !== undefined) {
+          window.clearTimeout(desktopContextRetryTimer)
+          desktopContextRetryTimer = undefined
+        }
+      })
+      .catch(() => {
+        if (disposed) return
+        if (pendingDesktopContext !== serialized || lastDesktopContext === serialized) return
+        if (desktopContextRetryTimer !== undefined) window.clearTimeout(desktopContextRetryTimer)
+        desktopContextRetryTimer = window.setTimeout(() => {
```
Comment (Astro-Han) [inline packages/app/src/pages/session.tsx:376]: Retry mechanism may loop indefinitely if IPC fails. Add max retry count or exponential backoff.

File: packages/app/src/app.tsx [hunk 9]
```diff
@@ -122,13 +125,39 @@ function RouterRoot(props: ParentProps<{ appChildren?: JSX.Element }>) {
...
+          locale: language.locale(),
+        }),
+      )
+      .catch(() => undefined)
+  })
+
+  return null
+}
+
+function isSessionRoute(pathname: string) {
```
Comment (Astro-Han) [inline packages/app/src/app.tsx:208]: split/filter parsing is fragile for edge cases like /session (no ID). Use pathname.match for robustness.

**Review by Astro-Han — COMMENTED** [review]
Additional review for modified files.

**Review by Astro-Han — COMMENTED** [review]
## Review Summary

This PR adds menu localization, desktop context tracking, problem report integration, and updater refactoring. Overall the implementation is solid, but I have several nitpicks and minor concerns.

### Key Issues

1. **Cross-package imports in preload/types.ts** - Imports from `packages/app` could create circular dependency risks. The preload package is typically a leaf in the dependency graph.

2. **Clipboard size limit** - The 5MB default for problem reports is quite large for clipboard operations. Most clipboard implementations struggle with content above 1-2MB.

3. **Silent error handling** - Several places catch errors silently (`.catch(() => undefined)`) which could hide important failures.

### Minor Nitpicks

- **Unnecessary optional chaining** in `menuLabel()`: `labels[locale]?.[key] ?? labels.en[key]` - since `MenuLocale` is a union type `"en" | "zh"`, both keys are guaranteed to exist.

- **Missing debug logs for locale fallbacks** - `feedbackDialogLabels()` and `updaterDialogLabels()` both have runtime fallbacks for unexpected locale values. Consider adding a `console.warn` or logger call to help debug cross-process boundary issues.

- **Reference vs value comparison** in `desktop-context-store.ts`: The `delete` method compares `removed === mostRecent` by reference, not by value. Two context objects with identical values but different references would be treated as different.

- **Hardcoded accelerators** - Strings like `"Shift+Cmd+S"` are hardcoded throughout `menu-template.ts`. These should be documented or extracted to a constants file.

- **Retry without backoff** in `session.tsx` - The `syncDesktopContext` retry logic uses a fixed 250ms delay without exponential backoff, which could retry indefinitely for persistent errors.

### Documentation Suggestions

- The comment at `menu-i18n.ts:10` says "Keep an explicit stored locale, including English" but could be clearer about the intent.

- The `mergeLatest` function in `finalize-latest-yml.ts` takes the last item as metadata base - the reasoning should be documented more clearly.

Overall, the PR is well-structured with good test coverage. These are mostly nitpicks that could improve maintainability.

File: packages/desktop-electron/src/main/menu-labels.ts [hunk 10]
```diff
@@ -0,0 +1,111 @@
...
+    openProject: "打开项目...",
+    newWindow: "新建窗口",
+    toggleSidebar: "切换侧边栏",
+    toggleTerminal: "切换终端",
+    toggleFileTree: "切换文件树",
+    back: "后退",
+    forward: "前进",
+    previousSession: "上一个会话",
+    nextSession: "下一个会话",
+    previousProject: "上一个项目",
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/menu-labels.ts:73]: The optional chaining `labels[locale]?.[key]` is unnecessary since `MenuLocale` is a union type `"en" | "zh"` and TypeScript guarantees both keys exist in `labels`. The fallback `?? labels.en[key]` would never execute for valid `MenuLocale` values.

File: packages/desktop-electron/src/main/menu-labels.ts [hunk 11]
```diff
@@ -0,0 +1,111 @@
...
+  }
+  if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
+    const locale = (parsed as Record<string, unknown>).locale
+    return parseMenuLocale(locale)
+  }
+  return "en"
+}
+
+export function detectSystemMenuLocale(locale: string | null | undefined): MenuLocale {
+  if (locale?.toLowerCase().startsWith("zh")) return "zh"
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/menu-labels.ts:120]: The `parseStored` function catches JSON parse errors silently and returns the original value. Consider adding a debug log when JSON parsing fails to help diagnose malformed stored values during development.

File: packages/desktop-electron/src/main/feedback.ts [hunk 12]
```diff
@@ -0,0 +1,73 @@
...
+      failedMessage: "Could not copy the report or open the feedback form.",
+    },
+    zh: {
+      title: "复制问题报告？",
+      message:
+        "PawWork 会复制一份问题报告到剪贴板，并打开反馈表单。报告可能包含应用诊断信息、最近应用日志、当前会话消息、工具输出、文件名、包含系统用户名的路径和文件片段。提交前请先检查。",
+      confirm: "复制报告并打开表单",
+      cancel: "取消",
+      failedTitle: "问题报告失败",
+      failedMessage: "无法复制报告或打开反馈表单。",
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/feedback.ts:35]: The `feedbackDialogLabels` and `updaterDialogLabels` functions both have runtime fallbacks for unexpected locale values. Consider adding a `console.warn` or logger call when encountering an unexpected locale to help debug cross-process boundary issues.

File: packages/desktop-electron/src/main/problem-report.ts [hunk 13]
```diff
@@ -0,0 +1,172 @@
...
+
+export type SessionExport =
+  | { status: "none" }
+  | { status: "failed"; error: string }
+  | { status: "ok"; info: unknown; messages: unknown[] }
+
+type Input = {
+  diagnostics: ProblemReportDiagnostics
+  logTail: string
+  sessionExport: SessionExport
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/problem-report.ts:36]: The 5MB default for problem reports is quite large for clipboard operations. Most clipboard implementations struggle with content above 1-2MB. Consider documenting why 5MB is chosen, or reducing to a more clipboard-friendly size like 2MB.

File: packages/desktop-electron/src/main/desktop-context-store.ts [hunk 14]
```diff
@@ -0,0 +1,23 @@
...
+      mostRecent = context
+    },
+    delete(windowID: number) {
+      const removed = contexts.get(windowID)
+      contexts.delete(windowID)
+      if (removed === mostRecent) mostRecent = [...contexts.values()].at(-1)
+    },
+    current(windowID?: number | null) {
+      if (windowID !== undefined && windowID !== null) return contexts.get(windowID) ?? fallback()
+      return mostRecent ?? fallback()
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/desktop-context-store.ts:22]: The `delete` method compares `removed === mostRecent` by reference, not by value. Two context objects with identical values but different references would be treated as different. If this is intentional, consider documenting it; otherwise, consider using a deep equality check or tracking by a serialized key.

File: packages/desktop-electron/src/preload/types.ts [hunk 15]
```diff
@@ -1,3 +1,9 @@
+import type { UpdateInfo } from "../../../app/src/context/platform"
```
Comment (Astro-Han) [inline packages/desktop-electron/src/preload/types.ts:1]: These imports cross package boundaries from `preload` to `app`. This could create circular dependency risks if `app` ever imports from `preload`. Consider defining shared types in a separate package or using re-exports.

File: packages/app/src/pages/session.tsx [hunk 16]
```diff
@@ -333,8 +334,54 @@ export default function Page() {
...
+          desktopContextRetryTimer = undefined
+          if (disposed || pendingDesktopContext !== serialized || lastDesktopContext === serialized) return
+          syncDesktopContext(context, serialized)
+        }, 250)
+      })
+  }
+
```
Comment (Astro-Han) [inline packages/app/src/pages/session.tsx:383]: The `syncDesktopContext` retry logic uses a fixed 250ms delay without exponential backoff. For persistent errors (e.g., IPC handler not registered), this could retry indefinitely. Consider adding a max retry count or exponential backoff.

File: packages/app/src/pages/session.tsx [hunk 17]
```diff
@@ -333,8 +334,54 @@ export default function Page() {
...
+  createEffect(() => {
+    if (!window.api?.setDesktopContext) return
```
Comment (Astro-Han) [inline packages/app/src/pages/session.tsx:385]: The `disposed` flag is a local variable that wont survive HMR (Hot Module Replacement) in development. If the component is re-mounted after HMR, the cleanup timer from the previous instance could still fire. Consider using a ref or a cleanup function that survives HMR.

File: packages/desktop-electron/src/main/menu-template.ts [hunk 18]
```diff
@@ -0,0 +1,130 @@
...
+        { type: "separator" },
+        { label: t("previousProject"), accelerator: "Cmd+Option+Up", click: () => deps.trigger("project.previous") },
+        { label: t("nextProject"), accelerator: "Cmd+Option+Down", click: () => deps.trigger("project.next") },
+      ],
+    },
+    { role: "windowMenu" },
+    {
+      label: t("help"),
+      submenu: helpSubmenu,
+    },
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/menu-template.ts:127]: Accelerator strings like `"Shift+Cmd+S"` are hardcoded throughout this file. These should be documented or extracted to a constants file for consistency and easier maintenance.

File: packages/desktop-electron/src/main/menu-i18n.ts [hunk 19]
```diff
@@ -0,0 +1,14 @@
+import { getStore } from "./store"
+import { detectSystemMenuLocale, parseMenuLocale, type MenuLocale } from "./menu-labels"
+
+export function readStoredMenuLocale(systemLocale: string | null | undefined): MenuLocale {
+  const raw = getStore("opencode.global.dat").get("language")
+  const stored = parseMenuLocale(raw)
+  // Keep an explicit stored locale, including English; otherwise detect from the OS locale.
+  if (raw) return stored
+  return detectSystemMenuLocale(systemLocale)
+}
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/menu-i18n.ts:10]: The comment says "Keep an explicit stored locale, including English" but could be clearer about the intent. Consider expanding to: "Preserve explicit user preference (including English for users who explicitly chose it); otherwise auto-detect from OS locale."

File: .github/workflows/build.yml [hunk 20]
```diff
@@ -297,19 +299,62 @@ jobs:
...
         env:
           APPLE_API_KEY_CONTENT: ${{ secrets.APPLE_API_KEY }}
 
+      - name: Download existing updater metadata
+        if: ${{ (runner.os == 'macOS' && (inputs.phase == 'finalize' || inputs.phase == 'full') && inputs.arch == matrix.arch_label) || (runner.os == 'Windows' && inputs.phase == 'full') }}
+        shell: bash
+        run: |
+          set -euo pipefail
+
+          existing_dir="$RUNNER_TEMP/existing-latest-yml"
```
Comment (Astro-Han) [inline .github/workflows/build.yml:331]: The condition for downloading existing metadata is complex: `${{ (runner.os == macOS && (inputs.phase == finalize || inputs.phase == full) && inputs.arch == matrix.arch_label) || (runner.os == Windows && inputs.phase == full) }}`. Consider adding a comment explaining why macOS downloads during finalize phase while Windows only downloads during full phase.

File: packages/desktop-electron/scripts/finalize-latest-yml.ts [hunk 21]
```diff
@@ -76,18 +77,88 @@ async function read(subdir: string, filename: string): Promise<LatestYml | undef
...
 const output: Record<string, string> = {}
+const tag = `v${version}`
+const tmp = process.env.RUNNER_TEMP ?? "/tmp"
 
 // Windows: merge arm64 + x64 into single file
 const winX64 = await read("latest-yml-x86_64-pc-windows-msvc", "latest.yml")
 const winArm64 = await read("latest-yml-aarch64-pc-windows-msvc", "latest.yml")
 if (winX64 || winArm64) {
   const base = winArm64 ?? winX64!
-  output["latest.yml"] = serialize({
```
Comment (Astro-Han) [inline packages/desktop-electron/scripts/finalize-latest-yml.ts:86]: The `mergeLatest` function takes the last item as metadata base with comment "live data wins over cached snapshots". This reasoning should be documented more clearly - explain that the last item contains the most recent releaseDate and other metadata that should not be overwritten by stale cached data.

File: packages/desktop-electron/src/main/desktop-context-store.ts (hunk 2 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/desktop-context-store.ts:11]: Kept this as-is. The delete is not redundant here because Map insertion order is used as the fallback order after deleting the current most recent context. Removing it broke `desktop-context-store.test.ts`, so I restored it and added a comment for the reference-identity check below.

File: packages/desktop-electron/src/main/menu-i18n.ts (hunk 3 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/menu-i18n.ts:16]: Documented the expected write format. `writeStoredMenuLocale` keeps the renderer language payload shape, while `parseMenuLocale` intentionally accepts legacy raw strings for compatibility.

File: packages/desktop-electron/src/main/problem-report.ts (hunk 4 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/problem-report.ts:70]: Fixed. The truncation guard now checks both `null` and `undefined` before replacing session info.

File: packages/desktop-electron/src/main/problem-report.ts (hunk 5 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/problem-report.ts:130]: Fixed. The parser no longer relies on one non-greedy regex capture. It now finds the JSON fence line-by-line and validates candidates with `JSON.parse`.

File: packages/desktop-electron/src/main/menu.ts (hunk 6 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/menu.ts]: Fixed. Switched the menu external-link failure path from `console.warn` to `electron-log`.

File: packages/desktop-electron/src/main/index.ts (hunk 7 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/index.ts]: Fixed. Feedback context is now normalized before reading locale, diagnostics, or session export context, instead of relying on a type assertion.

File: packages/app/src/pages/session.tsx (hunk 8 above)
Comment (Astro-Han) [reply packages/app/src/pages/session.tsx:376]: Fixed. Desktop context sync now has a max retry count and exponential backoff.

File: packages/app/src/app.tsx (hunk 9 above)
Comment (Astro-Han) [reply packages/app/src/app.tsx:208]: Fixed. The session-route guard now uses an explicit route-shape regex for `/:dir/session/:id?`.

File: packages/desktop-electron/src/main/menu-labels.ts (hunk 10 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/menu-labels.ts:73]: Leaving this fallback. It is intentionally defensive for runtime values crossing process boundaries, and the existing test covers `menuLabel("fr" as never, "file")`.

File: packages/desktop-electron/src/main/menu-labels.ts (hunk 11 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/menu-labels.ts:120]: Leaving this quiet. This parser intentionally accepts legacy raw string values, so a JSON parse miss is a normal compatibility path rather than an error condition worth logging.

File: packages/desktop-electron/src/main/feedback.ts (hunk 12 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/feedback.ts:35]: Leaving this without logging. These label helpers are pure lookup functions and already have tests for unexpected runtime locale values. Logging here would add side effects to a hot UI path.

File: packages/desktop-electron/src/main/problem-report.ts (hunk 13 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/problem-report.ts:36]: Documented the bound. I kept the 5MB limit because this report includes recent logs plus session snippets and already trims aggressively before returning.

File: packages/desktop-electron/src/main/desktop-context-store.ts (hunk 14 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/desktop-context-store.ts:22]: Documented. The reference check is intentional because `removed` is fetched from the same Map before deletion, so identical-by-value objects from other windows should not affect the most-recent pointer.

File: packages/desktop-electron/src/preload/types.ts (hunk 15 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/preload/types.ts:1]: Leaving this for now. These are type-only imports, so they do not create a runtime dependency cycle. A dedicated shared types package is a larger repo-structure change and out of scope for this PR.

File: packages/app/src/pages/session.tsx (hunk 16 above)
Comment (Astro-Han) [reply packages/app/src/pages/session.tsx:383]: Fixed. The retry path now uses a maximum retry count plus exponential backoff instead of a fixed unbounded 250ms loop.

File: packages/app/src/pages/session.tsx (hunk 17 above)
Comment (Astro-Han) [reply packages/app/src/pages/session.tsx:385]: Leaving this as-is. The timer is registered inside the component lifecycle and cleared in `onCleanup`; changing this specifically for HMR would add complexity for a dev-only path without changing production behavior.

File: packages/desktop-electron/src/main/menu-template.ts (hunk 18 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/menu-template.ts:127]: Leaving this as-is. The accelerators are centralized in the menu template already, and extracting constants would add indirection without reducing current risk.

File: packages/desktop-electron/src/main/menu-i18n.ts (hunk 19 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/menu-i18n.ts:10]: Fixed. Expanded the comment to state that explicit user preference, including English, is preserved before OS detection.

File: .github/workflows/build.yml (hunk 20 above)
Comment (Astro-Han) [reply .github/workflows/build.yml:331]: Fixed. Added a workflow comment explaining the macOS finalize-phase path versus the Windows full-packaging path.

File: packages/desktop-electron/scripts/finalize-latest-yml.ts (hunk 21 above)
Comment (Astro-Han) [reply packages/desktop-electron/scripts/finalize-latest-yml.ts:86]: Fixed. Clarified that the last metadata item is used so fresh live releaseDate and version fields win over cached snapshots.

**Review by Astro-Han — COMMENTED** [review]
Thanks for this comprehensive PR. Below are a few nitpicks and suggestions for improvement. Overall the implementation is solid and well-tested.

File: packages/desktop-electron/src/main/menu-labels.ts [hunk 22]
```diff
@@ -0,0 +1,111 @@
...
+    view: "View",
+    go: "Go",
+    help: "Help",
+    checkForUpdates: "Check for Updates...",
+    reloadWindow: "Reload Window",
+    restart: "Restart",
+    newSession: "New Session",
+    openProject: "Open Project...",
+    newWindow: "New Window",
+    toggleSidebar: "Toggle Sidebar",
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/menu-labels.ts:41]: The `parseStored` helper returns the original string value if JSON parsing fails. This works for locale parsing because `parseMenuLocale` handles raw strings, but the function name suggests it always parses, which could mislead readers. Consider renaming to `tryParseStored` or documenting the fallback behavior in a comment.

File: packages/desktop-electron/src/main/desktop-context-store.ts [hunk 23]
```diff
@@ -0,0 +1,24 @@
+import type { DesktopContext } from "../preload/types"
+
+export function createDesktopContextStore(fallback: () => DesktopContext) {
+  const contexts = new Map<number, DesktopContext>()
+  let mostRecent: DesktopContext | undefined
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/desktop-context-store.ts:5]: The `contexts.delete(windowID)` before `contexts.set(windowID, context)` is unnecessary. `Map.set` overwrites existing entries atomically, so the explicit delete adds an extra operation. This works correctly but could be simplified to just `contexts.set(windowID, context)`.

File: packages/desktop-electron/src/preload/types.ts [hunk 24]
```diff
@@ -1,3 +1,9 @@
...
+import type { DesktopContext } from "../../../app/src/utils/desktop-context"
```
Comment (Astro-Han) [inline packages/desktop-electron/src/preload/types.ts:2]: Importing `UpdateInfo` and `DesktopContext` from `../../../app/src/` creates a cross-package type dependency from `preload` to `app`. This works at runtime but couples the packages. If these types evolve, both packages must stay synchronized. Consider moving shared types to a common location (e.g., a `types` package or under `preload/types.ts` with the definitions owned there).

File: .github/workflows/build.yml [hunk 25]
```diff
@@ -297,19 +299,63 @@ jobs:
...
+
+          download_or_warn() {
+            local pattern="$1"
+            local err="$RUNNER_TEMP/${pattern}.err"
+            if gh release download "$tag" --pattern "$pattern" --dir "$existing_dir" --repo "$GITHUB_REPOSITORY" 2>"$err"; then
+              return 0
+            fi
+            if grep -qiE 'no assets to download|no matches found|no assets match|could not find any assets' "$err"; then
+              echo "No existing $pattern found; expected for first release."
+              return 0
```
Comment (Astro-Han) [inline .github/workflows/build.yml:343]: The error pattern matching in `download_or_warn` relies on specific `gh` CLI error message text (`no assets to download`, `no matches found`, etc.). These strings could change across `gh` versions, making this check fragile. Consider checking the exit code or using a more robust error classification strategy.

File: packages/desktop-electron/scripts/finalize-latest-yml.ts [hunk 26]
```diff
@@ -76,18 +77,88 @@ async function read(subdir: string, filename: string): Promise<LatestYml | undef
...
+  return data
+}
+
+async function downloadExisting(tag: string, filename: string) {
+  const configured = process.env.EXISTING_LATEST_YML_DIR
+  const cached = assertSameVersion(
+    "EXISTING_LATEST_YML_DIR",
+    filename,
+    configured ? await readFile(path.join(configured, filename)) : undefined,
+  )
```
Comment (Astro-Han) [inline packages/desktop-electron/scripts/finalize-latest-yml.ts:134]: The `isMissingAssetError` function pattern matches CLI error text. Same concern as the workflow: error message strings are not guaranteed stable. If `gh` changes wording, this function may fail to recognize benign errors and incorrectly propagate them.

File: packages/desktop-electron/src/main/problem-report.ts [hunk 27]
```diff
@@ -0,0 +1,184 @@
...
+    electronVersion: truncateString(diagnostics.electronVersion, stringLimit),
+    locale: truncateString(diagnostics.locale, stringLimit),
+    route: truncateString(diagnostics.route, stringLimit),
+    directory: diagnostics.directory === null ? null : truncateString(diagnostics.directory, stringLimit),
+    sessionID: diagnostics.sessionID === null ? null : truncateString(diagnostics.sessionID, stringLimit),
+    logPath: truncateString(diagnostics.logPath, stringLimit),
+  }
+}
+
+export function buildProblemReport(input: Input, options: Options = {}) {
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/problem-report.ts:149]: The truncation strategy removes from the front of messages array (`messages.slice(remove)`), discarding the oldest messages first. This preserves newer messages which are likely more relevant for debugging. The approach is sound, but consider documenting the LIFO truncation order explicitly for maintainers.

File: packages/desktop-electron/src/main/problem-report.ts [hunk 28]
```diff
@@ -0,0 +1,184 @@
...
+  const maxBytes = Math.floor(options.maxBytes ?? DEFAULT_MAX_BYTES)
+  if (!Number.isFinite(maxBytes) || maxBytes <= 0) throw new Error("maxBytes must be a positive finite number")
+  let diagnostics = input.diagnostics
+  let logTail = input.logTail
+  let messages = sessionMessages(input.sessionExport)
+  let sessionInfo = input.sessionExport.status === "ok" ? input.sessionExport.info : undefined
+  let omittedMessages = 0
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/problem-report.ts:158]: The log truncation also removes from the front (`logTail.slice(remove)`), discarding older log entries first. This is consistent with message truncation. However, log entries often have timestamps, and removing older entries might lose crucial error context. Consider truncating from both ends or keeping the most recent ERROR-level entries.

File: packages/app/src/pages/session.tsx [hunk 29]
```diff
@@ -333,8 +334,65 @@ export default function Page() {
...
+  let disposed = false
+
+  const syncDesktopContext = (context: DesktopContext, serialized: string) => {
+    if (disposed) return
+    const setDesktopContext = window.api?.setDesktopContext
+    if (!setDesktopContext) return
+    void setDesktopContext(context)
+      .then(() => {
+        if (disposed) return
+        if (pendingDesktopContext !== serialized) return
```
Comment (Astro-Han) [inline packages/app/src/pages/session.tsx:356]: The retry variables (`lastDesktopContext`, `pendingDesktopContext`, `desktopContextRetryTimer`, `desktopContextRetryCount`, `disposed`) are closure variables within the component function scope. This is correct for SolidJS but could be hard to debug if context sync issues arise. Consider extracting this logic into a dedicated hook or utility for better separation and testability.

File: packages/desktop-electron/src/main/feedback.ts [hunk 30]
```diff
@@ -0,0 +1,73 @@
...
+  diagnostics: (context?: unknown) => ProblemReportDiagnostics
+  logTail: () => string
+  sessionExport: (context?: unknown) => Promise<SessionExport>
+  onError?: (error: unknown) => Promise<void> | void
+}
+
+export function feedbackDialogLabels(locale: MenuLocale) {
+  const labels = {
+    en: {
+      title: "Copy problem report?",
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/feedback.ts:20]: The `createFeedbackHandler` returns an async function that catches all errors internally and only reports via `deps.onError`. Callers cannot distinguish between success and failure (e.g., for UI feedback) unless they provide an `onError` callback. Consider returning a result status or throwing for critical failures that should block subsequent actions.

File: packages/desktop-electron/src/main/menu-labels.ts (hunk 22 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/menu-labels.ts:41]: Renamed this to `parseStoredOrRaw` in `c1e7e7495` so the fallback behavior is explicit.

File: packages/desktop-electron/src/main/desktop-context-store.ts (hunk 23 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/desktop-context-store.ts:5]: I checked this by removing the delete and running `bun test src/main/desktop-context-store.test.ts src/main/menu-labels.test.ts src/main/problem-report.test.ts`. It fails the most-recently-updated fallback test because `Map.set` does not refresh insertion order for an existing key. Keeping `delete` preserves the intended chronological update order.

File: packages/desktop-electron/src/preload/types.ts (hunk 24 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/preload/types.ts:2]: Leaving this as-is for this PR. The current import is type-only and was introduced to avoid duplicating the IPC contract. Moving both app and desktop types into a new shared location would be a broader package-boundary refactor than this conflict/review pass, and there is no existing shared types package to use here.

File: .github/workflows/build.yml (hunk 25 above)
Comment (Astro-Han) [reply .github/workflows/build.yml:343]: Keeping this approach. `gh release download` does not provide a reliable asset-missing exit code separate from other failures, so stderr classification is the available boundary. The pattern is intentionally restricted to asset-specific messages, and auth, repo, tag, network, and generic 404 errors still print stderr and return non-zero.

File: packages/desktop-electron/scripts/finalize-latest-yml.ts (hunk 26 above)
Comment (Astro-Han) [reply packages/desktop-electron/scripts/finalize-latest-yml.ts:134]: Same reasoning as the workflow. `isMissingAssetError` now only accepts asset-specific messages such as no assets or no matches. Generic not-found and 404 cases are no longer treated as benign, so wrong tag, repo access, or API failures still throw instead of falling back to cached metadata.

File: packages/desktop-electron/src/main/problem-report.ts (hunk 27 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/problem-report.ts:149]: Documented the truncation policy in `c1e7e7495`: the report keeps newest session messages and log bytes because failures usually happen near the end.

File: packages/desktop-electron/src/main/problem-report.ts (hunk 28 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/problem-report.ts:158]: Kept this consistent with the message policy and documented it in `c1e7e7495`. For this report, preserving the newest tail is the safer default than splitting both ends, since the user-triggered failure context is expected near the end. More selective ERROR retention would require structured log parsing, which is out of scope for this PR.

File: packages/app/src/pages/session.tsx (hunk 29 above)
Comment (Astro-Han) [reply packages/app/src/pages/session.tsx:356]: Leaving this inline for now. The retry state is bounded (`desktopContextMaxRetries = 5`), uses exponential backoff, checks stale completions before mutating timer state, and clears timers on cleanup. There is only one call site, so extracting a hook now would add indirection without reducing shared complexity.

File: packages/desktop-electron/src/main/feedback.ts (hunk 30 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/feedback.ts:20]: Keeping the internal catch. This handler is wired from menu commands and does not have a downstream UI state consumer; the caller supplies `onError`, which logs and shows the user-visible failure dialog. Returning a status would add an unused contract here.

File: packages/desktop-electron/src/preload/types.ts (hunk 24 above)
Comment (Astro-Han) [inline packages/desktop-electron/src/preload/types.ts:2]: Cross-package type dependency persists. Importing `UpdateInfo` and `DesktopContext` from `../../../app/src/` couples preload to app. A refactoring to move these types to a shared location would reduce coupling, but this is acceptable for now given the tight integration between these packages.

File: packages/desktop-electron/src/main/desktop-context-store.ts (hunk 23 above)
Comment (Astro-Han) [inline packages/desktop-electron/src/main/desktop-context-store.ts:5]: The explicit `contexts.delete(windowID)` before `contexts.set(windowID, context)` is redundant. `Map.set` overwrites existing entries atomically. While harmless, removing it would be cleaner.

File: packages/desktop-electron/scripts/finalize-latest-yml.ts (hunk 26 above)
Comment (Astro-Han) [inline packages/desktop-electron/scripts/finalize-latest-yml.ts:134]: The `isMissingAssetError` regex matches CLI error message strings. If `gh` CLI changes error wording in future versions, this check may break. Consider documenting this fragility or adding a fallback for unrecognized error patterns.

File: packages/desktop-electron/src/main/feedback.ts (hunk 30 above)
Comment (Astro-Han) [inline packages/desktop-electron/src/main/feedback.ts:20]: The `createFeedbackHandler` returns an async function that catches all errors and reports only via `deps.onError?.(error)`. Callers receive no indication of success or failure unless they inspect side effects (clipboard, browser). Consider returning a status enum like `{ status: 'success' | 'cancelled' | 'failed' }` for better observability.

File: packages/desktop-electron/src/main/index.ts [hunk 31]
```diff
@@ -69,11 +76,133 @@ let mainWindow: BrowserWindow | null = null
...
+    locale: value.locale === "zh" ? "zh" : "en",
+  }
+}
+
+function feedbackContext(context: unknown): DesktopContext {
+  return context === undefined ? currentDesktopContext() : normalizeDesktopContext(context)
+}
+
+const reportProblem = createFeedbackHandler({
+  feedbackUrl: FEEDBACK_FORM_URL,
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/index.ts:174]: The `sessionExport` function uses a 10-second timeout via `Promise.race`. If the session is large or the server is slow, this may abort prematurely. Consider making the timeout configurable or matching the server's actual response time patterns.

File: packages/opencode/test/config/config.test.ts [hunk 32]
```diff
@@ -1382,6 +1382,7 @@ it.live(
     expect(await Filesystem.exists(gitignorePath)).toBe(true)
     expect(await Filesystem.readText(gitignorePath)).toContain("package-lock.json")
   }),
+  60_000,
 )
```
Comment (Astro-Han) [inline packages/opencode/test/config/config.test.ts:1386]: Adding a 60_000ms timeout to an existing test appears unrelated to this PR's changes. If this is addressing a flaky test issue, consider noting it in a separate commit or PR with context about why the timeout increase is needed.

File: packages/desktop-electron/src/main/server.test.ts [hunk 33]
```diff
@@ -20,7 +26,26 @@ mock.module("./store", () => ({
...
   getUserShell: () => null,
+  isNushell: (shell: string) => {
+    const name = path.basename(shell).toLowerCase()
+    const raw = shell.toLowerCase()
+    return name === "nu" || name === "nu.exe" || raw.endsWith("\\nu.exe")
+  },
   loadShellEnv: () => ({}),
+  mergeShellEnv: (shell: Record<string, string> | null, env: Record<string, string>) => ({
+    ...(shell || {}),
+    ...env,
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/server.test.ts:37]: The mock additions for `isNushell`, `mergeShellEnv`, and `parseShellEnv` in `server.test.ts` are thorough but seem unrelated to the PR's core changes (desktop menu, feedback, updater metadata). If these mocks were added to fix test isolation issues, they could be split into a separate preparatory commit.

**Review by Astro-Han — COMMENTED** [review]
Second pass review. The previous concerns have been addressed (renamed `parseStored` to `parseStoredOrRaw`, added comment explaining truncation order, added `mock.restore()` in tests). Remaining nitpicks below.

File: packages/desktop-electron/src/preload/types.ts (hunk 24 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/preload/types.ts:2]: Keeping this for now. This is a type-only import and avoids duplicating the IPC contract in this PR. Moving these types into a new shared package or shared module would be a broader package-boundary refactor, so I agree it is acceptable for this PR.

File: packages/desktop-electron/src/main/desktop-context-store.ts (hunk 23 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/desktop-context-store.ts:5]: I verified this by removing the delete and rerunning the desktop context store tests. It fails the most-recently-updated fallback case because `Map.set` does not refresh insertion order for an existing key. The delete is intentional here so the map values order tracks update order.

File: packages/desktop-electron/scripts/finalize-latest-yml.ts (hunk 26 above)
Comment (Astro-Han) [reply packages/desktop-electron/scripts/finalize-latest-yml.ts:134]: Documented this constraint in `532561c52`. The comment now states that `gh release download` has no asset-missing exit code, so the matcher must stay narrow and let generic 404, release, repo, and auth failures propagate.

File: packages/desktop-electron/src/main/feedback.ts (hunk 30 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/feedback.ts:20]: Leaving the async handler shape unchanged. The only current caller is the menu action, and failure is already surfaced through `deps.onError` in `index.ts` with logging plus a visible dialog. A returned status would currently be unused API surface.

File: packages/desktop-electron/src/main/index.ts (hunk 31 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/index.ts:174]: Keeping the fixed timeout. This path runs from a user-triggered feedback action, so it needs a bounded failure mode rather than waiting indefinitely on a large or stuck session export. The report still records export failure and continues with diagnostics and logs.

File: packages/opencode/test/config/config.test.ts (hunk 32 above)
Comment (Astro-Han) [reply packages/opencode/test/config/config.test.ts:1386]: This was added for CI stabilization after the rebased PR exposed a repeated Windows full-suite timeout in this specific live config test. It is already isolated in `fcac32f26` (`fix: stabilize desktop server tests on windows`), separate from the product commits.

File: packages/desktop-electron/src/main/server.test.ts (hunk 33 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/server.test.ts:37]: These mock additions were also part of the Windows CI stabilization commit `fcac32f26`. The reason is test isolation: `server.test.ts` mocks `./shell-env`, and without faithfully exporting the full shell-env surface the mock leaks into `shell-env.test.ts` under the Windows test run.

File: packages/desktop-electron/src/main/menu-labels.ts [hunk 34]
```diff
@@ -0,0 +1,111 @@
...
+    back: "后退",
+    forward: "前进",
+    previousSession: "上一个会话",
+    nextSession: "下一个会话",
+    previousProject: "上一个项目",
+    nextProject: "下一个项目",
+    pawworkOnGithub: "PawWork 在 GitHub",
+    reportProblem: "报告问题",
+    openGithubIssue: "打开 GitHub Issue",
+  },
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/menu-labels.ts:78]: The `menuLabel` function has a triple fallback: `labels[locale]?.[key] ?? labels.en[key] ?? key`. Returning `key` as the final fallback means users will see raw key strings like `"toggleFileTree"` if a new label key is added without updating the dictionary. Consider logging a warning in development builds or throwing in dev mode to catch missing labels early.

File: packages/desktop-electron/src/main/menu-template.ts [hunk 35]
```diff
@@ -0,0 +1,130 @@
...
+
+  if (feedbackEnabled) {
+    helpSubmenu.push({ label: t("reportProblem"), click: () => deps.reportProblem() })
+  }
+
+  helpSubmenu.push({ label: t("openGithubIssue"), click: () => deps.openExternal(githubIssueUrl) })
+
+  return [
+    {
+      label: appName,
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/menu-template.ts:48]: The `githubIssueUrl` is hardcoded here while `FEEDBACK_FORM_URL` is injected via environment variable. For consistency and easier maintenance, consider moving both URLs to `constants.ts` or a shared configuration module.

File: packages/desktop-electron/src/main/menu.ts [hunk 36]
```diff
@@ -1,134 +1,28 @@
...
-  trigger: (id: string) => void
-  checkForUpdates: () => void
-  reload: () => void
-  relaunch: () => void
-  newWindow: () => void
-}
+type Deps = Omit<MenuTemplateDeps, "openExternal">
 
-export function createMenu(deps: Deps) {
+export function createMenu(deps: Deps, locale = readStoredMenuLocale(app.getLocale())) {
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/menu.ts:11]: The import uses `.js` extension (`electron-log/main.js`). While this is a common Electron pattern for ESM compatibility, it is inconsistent with other imports in this file (e.g., `./constants` without extension). Either adopt `.js` extensions consistently or document why this specific import requires it.

File: packages/desktop-electron/src/main/problem-report.ts [hunk 37]
```diff
@@ -0,0 +1,185 @@
+// Bound clipboard payloads while preserving recent logs and session snippets for diagnosis.
+const DEFAULT_MAX_BYTES = 5 * 1024 * 1024
+
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/problem-report.ts:4]: The top-level comment "Bound clipboard payloads..." explains the module purpose, but `DEFAULT_MAX_BYTES` is defined immediately after with no inline explanation. Consider adding a comment like `// 5 MB default limit for clipboard payload size` to clarify what this constant controls.

File: packages/app/src/pages/session.tsx [hunk 38]
```diff
@@ -333,8 +334,65 @@ export default function Page() {
   const prompt = usePrompt()
   const comments = useComments()
   const terminal = useTerminal()
+  const location = useLocation()
   const [searchParams, setSearchParams] = useSearchParams<{ prompt?: string }>()
   const { params, sessionKey, tabs, view } = useSessionLayout()
+  const desktopContextMaxRetries = 5
+  let lastDesktopContext = ""
```
Comment (Astro-Han) [inline packages/app/src/pages/session.tsx:343]: The retry logic uses exponential backoff with delays: 250, 500, 1000, 2000, 4000ms. With 5 retries, total potential wait time is ~7.75 seconds for a simple IPC call failure. Consider reducing the base delay or max retries, or document why this aggressive retry strategy is necessary.

File: packages/app/src/pages/session.tsx [hunk 39]
```diff
@@ -333,8 +334,65 @@ export default function Page() {
   const prompt = usePrompt()
```
Comment (Astro-Han) [inline packages/app/src/pages/session.tsx:334]: Module-level variables in a SolidJS component (`desktopContextMaxRetries`, `lastDesktopContext`, etc.) could cause state leakage if the component is remounted. While this page component typically exists once, adding a brief comment explaining why module-level state is safe here would help future readers.

File: packages/desktop-electron/src/main/index.ts [hunk 40]
```diff
@@ -263,6 +394,21 @@ async function initialize() {
   overlay?.close()
 }
 
+function focusedMenuLocale() {
+  const focused = BrowserWindow.getFocusedWindow()
+  if (!focused) return menuLocale
+  return desktopContexts.current(focused.id).locale
+}
+
+function syncMenuLocaleForWindow(win: BrowserWindow | null) {
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/index.ts:403]: The `syncMenuLocaleForWindow` function calls `wireMenu()` which recreates the entire menu on every locale change. If a user rapidly switches between windows with different locales, this could cause performance issues or visual flicker. Consider debouncing or checking if the menu actually needs rebuilding.

File: packages/desktop-electron/src/main/updater.ts [hunk 41]
```diff
@@ -0,0 +1,95 @@
...
+      releaseVersion: info?.version ?? null,
+      files: info?.files?.map((file) => file.url) ?? [],
+    })
+
+    if (!result.isUpdateAvailable) return { status: "none" }
+    if (!info?.version) return { status: "failed", reason: "metadata", message: "Update metadata has no version" }
+    if (!info.files || info.files.length === 0) {
+      return { status: "failed", reason: "metadata", message: "Update metadata has no files" }
+    }
+
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/updater.ts:59]: The `run` function logs "checking for updates" only when neither the disabled nor ready-update conditions apply. When returning a ready update (lines 56-57), no log entry is created. Consider adding a log call before returning the ready status for traceability.

File: packages/desktop-electron/src/main/updater-dialog-labels.ts [hunk 42]
```diff
@@ -0,0 +1,63 @@
...
+      buttons: ["Restart", "Later"],
+    },
+  },
+  zh: {
+    busy: {
+      title: "正在检查更新",
+      message: "PawWork 正在检查更新。",
+    },
+    disabled: {
+      title: "更新不可用",
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/updater-dialog-labels.ts:41]: The `ready.message` function handles `version === undefined` gracefully, but based on the controller logic in `updater.ts`, `version` should always be present when status is "ready". Consider using a type assertion or narrowing to make this contract explicit, rather than defensive undefined handling.

File: packages/desktop-electron/scripts/finalize-latest-yml.ts [hunk 43]
```diff
@@ -76,18 +77,90 @@ async function read(subdir: string, filename: string): Promise<LatestYml | undef
   return parse(await file.text())
 }
 
+async function readFile(filepath: string): Promise<LatestYml | undefined> {
+  const file = Bun.file(filepath)
+  if (!(await file.exists())) return undefined
+  return parse(await file.text())
```
Comment (Astro-Han) [inline packages/desktop-electron/scripts/finalize-latest-yml.ts:83]: The `mergeLatest` function uses `files.set(file.url, file)` which means on URL collision, the LAST source wins (iteration order). The comment "Use the last item as the metadata base" refers to the base object fields, not the files map. Consider adding an explicit comment like `// On URL collision, later items overwrite earlier entries` to clarify file deduplication behavior.

File: packages/app/src/pages/error.tsx [hunk 44]
```diff
@@ -225,6 +226,7 @@ export const ErrorPage: Component<ErrorPageProps> = (props) => {
     checking: false,
     version: undefined as string | undefined,
```
Comment (Astro-Han) [inline packages/app/src/pages/error.tsx]: The `actionMessage` property declaration spans two visual lines due to the long type annotation, but the `as string | undefined` cast is on the same line as the previous property. Move `actionMessage:` to a new line for consistent formatting with other properties in this store definition.

File: packages/desktop-electron/src/main/feedback.ts [hunk 45]
```diff
@@ -0,0 +1,73 @@
...
+    { title: string; message: string; confirm: string; cancel: string; failedTitle: string; failedMessage: string }
+  >
+
+  // Runtime fallback for unexpected locale values crossing process boundaries.
+  return labels[locale] ?? labels.en
+}
+
+export function createFeedbackHandler(deps: FeedbackDeps) {
+  return async function reportProblem() {
+    try {
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/feedback.ts:49]: The `feedbackDialogLabels` function has a runtime fallback comment: "Runtime fallback for unexpected locale values crossing process boundaries." This is good defensive coding, but the condition that triggers this fallback is unclear. Document what scenarios could produce unexpected locale values (e.g., IPC serialization issues, manual config editing).

File: packages/desktop-electron/src/main/menu-i18n.ts [hunk 46]
```diff
@@ -0,0 +1,15 @@
...
+export function readStoredMenuLocale(systemLocale: string | null | undefined): MenuLocale {
+  const raw = getStore("opencode.global.dat").get("language")
+  const stored = parseMenuLocale(raw)
+  // Preserve an explicit user preference, including English; otherwise auto-detect from the OS locale.
+  if (raw) return stored
+  return detectSystemMenuLocale(systemLocale)
+}
+
+export function writeStoredMenuLocale(locale: MenuLocale) {
+  // Keep the renderer language payload shape while parseMenuLocale accepts legacy raw strings.
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/menu-i18n.ts]: The comment mentions "legacy raw strings" but does not describe what format those legacy strings were. Consider expanding the comment to: `// Legacy format stored raw locale strings like "zh" or "en". Current format wraps in { locale: "..." } for renderer compatibility.`

File: packages/desktop-electron/src/main/menu-labels.ts (hunk 34 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/menu-labels.ts:78]: Added a dev-only warning before falling back to the raw key so missing desktop labels are visible during development while production remains resilient.

File: packages/desktop-electron/src/main/menu-template.ts (hunk 35 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/menu-template.ts:48]: Moved the support links into `support-links.ts`, including `FEEDBACK_FORM_URL`, `PAWWORK_GITHUB_URL`, and `PAWWORK_GITHUB_ISSUE_URL`. This keeps the link configuration together without making the pure menu template import Electron-backed constants.

File: packages/desktop-electron/src/main/menu.ts (hunk 36 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/menu.ts:11]: Documented why this import keeps the `.js` suffix: `electron-log` exposes that ESM entrypoint with the suffix.

File: packages/desktop-electron/src/main/problem-report.ts (hunk 37 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/problem-report.ts:4]: Added an inline comment that `DEFAULT_MAX_BYTES` is the 5 MB clipboard payload limit.

File: packages/app/src/pages/session.tsx (hunk 38 above)
Comment (Astro-Han) [reply packages/app/src/pages/session.tsx:343]: Documented the retry window: five bounded retries cover transient IPC teardown/order races and avoid unbounded retry loops.

File: packages/app/src/pages/session.tsx (hunk 39 above)
Comment (Astro-Han) [reply packages/app/src/pages/session.tsx:334]: Added a comment clarifying that the retry state is per Page instance and cleanup cancels pending timers on unmount. These are component-local variables, not module-level shared state.

File: packages/desktop-electron/src/main/index.ts (hunk 40 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/index.ts:403]: Keeping the current implementation. `syncMenuLocaleForWindow` already checks `next === menuLocale` before calling `wireMenu()`, so it only rebuilds when the focused window locale actually changes. Debouncing would add delayed menu state after focus changes.

File: packages/desktop-electron/src/main/updater.ts (hunk 41 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/updater.ts:59]: Added a log entry for the cached ready-update path before returning the latched ready status.

File: packages/desktop-electron/src/main/updater-dialog-labels.ts (hunk 42 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/updater-dialog-labels.ts:41]: Keeping the defensive message fallback. The controller returns a version for `status: "ready"`, but the label helper is also directly tested and safe for accidental undefined input. Tightening this would not improve the controller contract.

File: packages/desktop-electron/scripts/finalize-latest-yml.ts (hunk 43 above)
Comment (Astro-Han) [reply packages/desktop-electron/scripts/finalize-latest-yml.ts:83]: Added an explicit comment above the files map noting that later items overwrite earlier entries on URL collision, so live/current metadata wins.

File: packages/app/src/pages/error.tsx (hunk 44 above)
Comment (Astro-Han) [reply packages/app/src/pages/error.tsx]: Replaced the inline `as string | undefined` casts with an explicit `ErrorPageStore` type, so the store shape is readable without long property casts.

File: packages/desktop-electron/src/main/feedback.ts (hunk 45 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/feedback.ts:49]: Expanded the fallback comment to name concrete cases: malformed IPC payloads or manually edited config.

File: packages/desktop-electron/src/main/menu-i18n.ts (hunk 46 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/menu-i18n.ts]: Expanded the storage comment to document both formats: legacy raw strings like `"zh"` or `"en"`, and the current wrapped `{ locale }` payload for renderer compatibility.

File: packages/desktop-electron/src/main/constants.ts [hunk 47]
```diff
@@ -4,6 +4,7 @@ import { PAWWORK_RUNTIME } from "./runtime-namespace"
 type Channel = "dev" | "beta" | "prod"
 const raw = import.meta.env.OPENCODE_CHANNEL
 export const CHANNEL: Channel = raw === "dev" || raw === "beta" || raw === "prod" ? raw : "dev"
+export const FEEDBACK_FORM_URL = (import.meta.env.PAWWORK_FEEDBACK_FORM_URL ?? "").trim()
```
[the remark this answers is not in the document]
Comment (Astro-Han) [reply packages/desktop-electron/src/main/constants.ts]: Added `normalizeFeedbackFormUrl` and coverage. `FEEDBACK_FORM_URL` now only enables the flow for valid HTTPS URLs; malformed, empty, or non-HTTPS values normalize to an empty string.

File: packages/desktop-electron/src/main/problem-report.ts [hunk 48]
```diff
@@ -0,0 +1,185 @@
...
+  for (let end = start + 1; end < lines.length; end++) {
+    if (lines[end] !== "```") continue
+    try {
+      return JSON.parse(lines.slice(start + 1, end).join("\n")) as Payload
+    } catch {
+      continue
+    }
+  }
+
+  throw new Error("Problem report JSON block not found")
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/problem-report.ts:308]: Updated `parseProblemReportPayload` to scan all `json` fences and skip malformed blocks. Added a regression test for an invalid first fence followed by a valid report.

File: packages/desktop-electron/src/preload/index.ts [hunk 49]
```diff
@@ -68,6 +67,14 @@ const api: ElectronAPI = {
...
   setZoomFactor: (factor) => ipcRenderer.invoke("set-zoom-factor", factor),
   setTitlebar: (theme) => ipcRenderer.invoke("set-titlebar", theme),
+  setDesktopContext: (context) => ipcRenderer.invoke("set-desktop-context", context),
+  initializeDesktopContext: (locale) =>
+    ipcRenderer.invoke("set-desktop-context", {
+      directory: null,
+      sessionID: null,
+      route: "/",
+      locale,
+    }),
```
[the remark this answers is not in the document]
Comment (Astro-Han) [reply packages/desktop-electron/src/preload/index.ts]: Extracted `invokeSetDesktopContext` in preload and routed both `setDesktopContext` and `initializeDesktopContext` through it.

File: packages/desktop-electron/src/renderer/index.tsx [hunk 50]
```diff
@@ -32,6 +32,12 @@ if (import.meta.env.DEV && !(root instanceof HTMLElement)) {
 }
 
 void initI18n()
+  .then((locale) => {
+    return window.api.initializeDesktopContext(locale)
+  })
+  .catch((error) => {
+    console.debug("[desktop] initializeDesktopContext failed", error)
+  })
```
[the remark this answers is not in the document]
Comment (Astro-Han) [reply packages/desktop-electron/src/renderer/index.tsx:42]: Split the promise handlers so `initializeDesktopContext` failures and `initI18n` failures log distinct messages.

File: packages/desktop-electron/src/main/menu-i18n.ts [hunk 51]
```diff
@@ -0,0 +1,16 @@
+import { getStore } from "./store"
+import { detectSystemMenuLocale, parseMenuLocale, type MenuLocale } from "./menu-labels"
+
+export function readStoredMenuLocale(systemLocale: string | null | undefined): MenuLocale {
+  const raw = getStore("opencode.global.dat").get("language")
+  const stored = parseMenuLocale(raw)
+  // Preserve an explicit user preference, including English; otherwise auto-detect from the OS locale.
+  if (raw) return stored
+  return detectSystemMenuLocale(systemLocale)
```
[the remark this answers is not in the document]
Comment (Astro-Han) [reply packages/desktop-electron/src/main/menu-i18n.ts]: Added `parseStoredMenuLocale` so only valid stored locale values count as explicit preferences. Malformed values now fall back to OS locale detection instead of forcing English.

**Comment by Astro-Han** [comment]
@coderabbitai review

File: packages/desktop-electron/src/main/menu-labels.ts [hunk 52]
```diff
@@ -0,0 +1,121 @@
...
+  }
+  return "en"
+}
+
+export function parseStoredMenuLocale(value: unknown): MenuLocale | undefined {
+  if (!value) return undefined
+  const stored = parseMenuLocale(value)
+  if (stored !== "en") return stored
+  return /\ben\b/i.test(String(value)) ? "en" : undefined
+}
```
[the remark this answers is not in the document]
Comment (Astro-Han) [reply packages/desktop-electron/src/main/menu-labels.ts:117]: Fixed. `parseStoredMenuLocale` now parses raw and wrapped stored payloads directly, so `{ locale: "en-US" }` is preserved as an explicit English preference while malformed or unsupported values still fall back to OS detection. Added coverage for object English and unsupported object payloads.

File: packages/desktop-electron/src/main/problem-report.ts [hunk 53]
```diff
@@ -0,0 +1,186 @@
...
+    diagnostics = truncateDiagnostics(input.diagnostics, diagnosticStringLimit)
+    omittedDiagnosticsBytes = Math.max(0, jsonBytes(input.diagnostics) - jsonBytes(diagnostics))
+    output = markdown(makePayload())
+    if (diagnosticStringLimit === 0) break
+    diagnosticStringLimit = Math.floor(diagnosticStringLimit / 2)
+  }
+
+  if (bytes(output) > maxBytes) {
+    throw new Error("Problem report exceeds maxBytes after truncation")
+  }
```
[the remark this answers is not in the document]
Comment (Astro-Han) [reply packages/desktop-electron/src/main/problem-report.ts]: Fixed. Failed session-export errors now participate in the payload truncation path, using the same size budget before diagnostics truncation. Added a regression test with an oversized failed export error to ensure the final markdown remains under `maxBytes`.

File: packages/desktop-electron/src/main/problem-report.ts [hunk 54]
```diff
@@ -0,0 +1,186 @@
...
+      if (lines[end] !== "```") continue
+      try {
+        return JSON.parse(lines.slice(start + 1, end).join("\n")) as Payload
+      } catch {
+        continue
+      }
+    }
+  }
+
+  throw new Error("Problem report JSON block not found")
```
[the remark this answers is not in the document]
Comment (Astro-Han) [reply packages/desktop-electron/src/main/problem-report.ts:308]: Fixed. `parseProblemReportPayload` now validates the parsed fenced JSON before returning `Payload`, including `reportVersion`, `generatedAt`, diagnostics, session export, and truncation shape. Invalid report-shaped JSON is skipped and ultimately rejected instead of being cast to `Payload`. Added a regression test for missing required fields.

**Comment by Astro-Han** [comment]
@coderabbitai review

**Comment by Astro-Han** [comment]
@coderabbitai review

File: packages/desktop-electron/src/main/problem-report.ts [hunk 55]
```diff
@@ -0,0 +1,267 @@
...
+    }
+  }
+
+  let diagnosticStringLimit = 512
+  while (bytes(output) > maxBytes && diagnosticStringLimit >= 0) {
+    diagnostics = truncateDiagnostics(input.diagnostics, diagnosticStringLimit)
+    omittedDiagnosticsBytes = Math.max(0, jsonBytes(input.diagnostics) - jsonBytes(diagnostics))
+    output = markdown(makePayload())
+    if (diagnosticStringLimit === 0) break
+    diagnosticStringLimit = Math.floor(diagnosticStringLimit / 2)
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/problem-report.ts:220]: The variable name `omittedSessionInfoBytes` is misleading here - it's also being used to track bytes truncated from the failed export error message (line 207-210), not just session info. Consider renaming to `omittedExportInfoBytes` or using separate counters for session info and error message truncation for better clarity.

File: packages/desktop-electron/src/main/menu.ts [hunk 56]
```diff
@@ -1,134 +1,29 @@
-import { Menu, shell } from "electron"
+import { app, Menu, shell } from "electron"
+// electron-log exposes this ESM entrypoint with the `.js` suffix.
+import log from "electron-log/main.js"
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/menu.ts:4]: The Chinese comment here is inconsistent with the rest of the codebase which uses English comments throughout. Consider translating to: "electron-log exposes this ESM entrypoint with the `.js` suffix." or removing it since the import path itself is self-explanatory.

File: packages/desktop-electron/src/main/problem-report.ts [hunk 57]
```diff
@@ -0,0 +1,267 @@
...
+function truncateString(value: string, limit: number) {
+  return value.length > limit ? value.slice(0, limit) : value
+}
+
+function truncateDiagnostics(diagnostics: ProblemReportDiagnostics, stringLimit: number): ProblemReportDiagnostics {
+  return {
+    ...diagnostics,
+    appVersion: truncateString(diagnostics.appVersion, stringLimit),
+    channel: truncateString(diagnostics.channel, stringLimit),
+    platform: truncateString(String(diagnostics.platform), stringLimit),
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/problem-report.ts:137]: This condition `sessionInfo !== null && sessionInfo !== undefined` can be simplified to `sessionInfo != null` which checks both null and undefined in one expression. The explicit dual check is redundant.

File: packages/desktop-electron/src/main/problem-report.ts [hunk 58]
```diff
@@ -0,0 +1,267 @@
+// Bound clipboard payloads while preserving recent logs and session snippets for diagnosis.
+// Default clipboard payload limit: 5 MB.
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/problem-report.ts:2]: A 5 MB clipboard limit may be too large for some environments. Some systems/applications have clipboard size limits or may have performance issues with very large clipboard content. Consider documenting this limit choice in the PR or reducing it to a more conservative value (e.g., 1-2 MB) if users report clipboard issues.

File: packages/desktop-electron/src/main/menu-labels.ts [hunk 59]
```diff
@@ -0,0 +1,129 @@
...
+    return parseMenuLocale(locale)
+  }
+  return "en"
+}
+
+export function parseStoredMenuLocale(value: unknown): MenuLocale | undefined {
+  if (!value) return undefined
+  const parsed = parseStoredOrRaw(value)
+  if (typeof parsed === "string") {
+    const normalized = parsed.toLowerCase().replaceAll("_", "-")
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/menu-labels.ts:108]: In production, if a label key is missing, the raw key string (e.g., "file") will be shown to users, which could be confusing. Consider either: (1) having a fallback English label for all keys, or (2) logging the missing key in production (not just DEV mode) to catch configuration errors early.

File: packages/desktop-electron/src/main/desktop-context-store.ts [hunk 60]
```diff
@@ -0,0 +1,24 @@
...
+
+  return {
+    set(windowID: number, context: DesktopContext) {
+      contexts.delete(windowID)
+      contexts.set(windowID, context)
+      mostRecent = context
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/desktop-context-store.ts:12]: The `set` method performs `delete` before `set` to update the Map key ordering. This is a subtle implementation detail that affects `mostRecent` tracking. Consider adding a brief comment explaining this behavior: "Delete before set ensures Map ordering reflects update sequence for mostRecent fallback." to make the intent clearer for future readers.

File: packages/desktop-electron/scripts/finalize-latest-yml.ts [hunk 61]
```diff
@@ -76,18 +77,91 @@ async function read(subdir: string, filename: string): Promise<LatestYml | undef
...
+
+  // Use the last item as the metadata base so fresh live releaseDate and version fields win over cached snapshots.
+  const base = present.at(-1)!
+  return {
+    version: base.version,
+    files: [...files.values()],
+    releaseDate: base.releaseDate,
+  }
+}
+
```
Comment (Astro-Han) [inline packages/desktop-electron/scripts/finalize-latest-yml.ts:104]: The mergeLatest function comment mentions "later items overwrite earlier entries" for URL collision, which is correct. However, the "base = present.at(-1)" comment says "fresh live releaseDate and version fields win over cached snapshots". This is clear, but consider also documenting what happens when live data has stale version (e.g., race condition) - should there be a version consistency check similar to assertSameVersion?

File: packages/desktop-electron/src/main/updater.ts [hunk 62]
```diff
@@ -0,0 +1,98 @@
...
+  | { status: "failed"; reason: "check" | "download" | "metadata"; message: string }
+
+type UpdateInfo = {
+  version?: string
+  files?: Array<{ url: string }>
+}
+
+type Deps = {
+  enabled: boolean
+  currentVersion: () => string
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/updater.ts:17]: The install() method sets updateReady and readyVersion to undefined/false AFTER calling deps.quitAndInstall(). If quitAndInstall() throws an exception (as tested in updater.test.ts line 83-88), the state is NOT cleared and a subsequent check() will still return ready. This is actually tested and documented in the test, but the ordering here is intentional - the update remains ready even if install fails. Consider documenting this behavior in a comment for clarity.

File: packages/desktop-electron/src/main/feedback.ts [hunk 63]
```diff
@@ -0,0 +1,74 @@
...
+      failedMessage: "Could not copy the report or open the feedback form.",
+    },
+    zh: {
+      title: "复制问题报告？",
+      message:
+        "PawWork 会复制一份问题报告到剪贴板，并打开反馈表单。报告可能包含应用诊断信息、最近应用日志、当前会话消息、工具输出、文件名、包含系统用户名的路径和文件片段。提交前请先检查。",
+      confirm: "复制报告并打开表单",
+      cancel: "取消",
+      failedTitle: "问题报告失败",
+      failedMessage: "无法复制报告或打开反馈表单。",
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/feedback.ts:35]: The warning message in English contains a very long single paragraph without line breaks. For dialog display, this might cause layout issues on smaller screens or in some dialog implementations. Consider splitting into multiple sentences with proper line breaks or ensuring the dialog can handle long text gracefully.

File: packages/desktop-electron/src/main/menu-i18n.ts [hunk 64]
```diff
@@ -0,0 +1,16 @@
...
+  const stored = parseStoredMenuLocale(raw)
+  // Preserve an explicit user preference, including English; otherwise auto-detect from the OS locale.
+  if (stored) return stored
+  return detectSystemMenuLocale(systemLocale)
+}
+
+export function writeStoredMenuLocale(locale: MenuLocale) {
+  // Legacy format stored raw locale strings like "zh" or "en"; current format
+  // wraps the locale for renderer language payload compatibility.
+  getStore("opencode.global.dat").set("language", JSON.stringify({ locale }))
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/menu-i18n.ts:15]: The comment mentions "Legacy format stored raw locale strings like 'zh' or 'en'" but the actual write format is JSON.stringify({ locale }). Consider updating the comment to clarify: "Legacy format stored raw locale strings; current format wraps locale in a JSON object for renderer compatibility. Both formats are readable by parseStoredMenuLocale." to better document the backward compatibility.

File: packages/desktop-electron/src/main/problem-report.ts [hunk 65]
```diff
@@ -0,0 +1,267 @@
...
+    generatedAt: new Date().toISOString(),
+    diagnostics,
+    logTail,
+    sessionExport: withFailedExportError(withMessages(withSessionInfo(input.sessionExport, sessionInfo), messages), failedExportError),
+    truncation: {
+      omittedMessages,
+      omittedLogBytes,
+      omittedSessionInfoBytes,
+      omittedDiagnosticsBytes,
+    },
```
Comment (Astro-Han) [inline packages/desktop-electron/src/main/problem-report.ts:176]: The truncation loop removes messages from the beginning (slice(remove)) but keeps the newest messages. The comment says "Keep the newest session messages because failures usually happen near the end". This is correct, but consider also mentioning that removing older messages preserves the most relevant context for debugging recent issues.

File: packages/desktop-electron/src/main/problem-report.ts [hunk 66]
```diff
@@ -0,0 +1,267 @@
...
+  route: string
+  directory: string | null
+  sessionID: string | null
+  logPath: string
+}
+
+export type SessionExport =
+  | { status: "none" }
+  | { status: "failed"; error: string }
+  | { status: "ok"; info: unknown; messages: unknown[] }
```
[the remark this answers is not in the document]
Comment (Astro-Han) [reply packages/desktop-electron/src/main/problem-report.ts:26]: Fixed. The report builder now sanitizes session export payloads before serialization. BigInt values are converted to strings and circular references become `[Circular]`, so `JSON.stringify` cannot break the feedback flow before truncation runs. Added a regression test for BigInt plus circular `info` and `messages`.

File: packages/desktop-electron/src/main/problem-report.ts (hunk 55 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/problem-report.ts:220]: Fixed with a separate `omittedFailedExportErrorBytes` counter. `omittedSessionInfoBytes` now only tracks removed ok-export info, and failed-export error truncation is reported independently.

File: packages/desktop-electron/src/main/menu.ts (hunk 56 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/menu.ts:4]: Already addressed in the current diff. The comment is now English: `electron-log exposes this ESM entrypoint with the .js suffix.`

File: packages/desktop-electron/src/main/problem-report.ts (hunk 57 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/problem-report.ts:137]: Fixed. The ok-export session info check now uses `sessionInfo != null`, which intentionally covers both null and undefined before removing oversized info.

File: packages/desktop-electron/src/main/problem-report.ts (hunk 58 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/problem-report.ts:2]: Leaving this unchanged for now. The report is still bounded and progressively truncated; reducing the cap without evidence would discard useful diagnostic context. If clipboard issues show up in real use, this is a good follow-up tuning knob.

File: packages/desktop-electron/src/main/menu-labels.ts (hunk 59 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/menu-labels.ts:108]: No code change here. For valid `MenuLabelKey` values, `labels.en[key]` is the production fallback and the raw key path is only for impossible or invalid runtime input. Keeping the warning dev-only avoids noisy production console output for a defensive edge path.

File: packages/desktop-electron/src/main/desktop-context-store.ts (hunk 60 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/desktop-context-store.ts:12]: Fixed. Added a short comment explaining that `delete` before `set` refreshes Map insertion order so the fallback follows the most recently updated window.

File: packages/desktop-electron/scripts/finalize-latest-yml.ts (hunk 61 above)
Comment (Astro-Han) [reply packages/desktop-electron/scripts/finalize-latest-yml.ts:104]: No change needed. `downloadExisting()` already runs `assertSameVersion` for both the cached snapshot and live GitHub metadata before merging, so stale-version live metadata fails before it can become the metadata base.

File: packages/desktop-electron/src/main/updater.ts (hunk 62 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/updater.ts:17]: Fixed. Added a short comment above `quitAndInstall()` documenting that the ready latch is intentionally kept if the install call throws before Electron starts installation.

File: packages/desktop-electron/src/main/feedback.ts (hunk 63 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/feedback.ts:35]: Fixed. The feedback consent copy now uses paragraph breaks in both English and Chinese, keeping the disclosure text easier to read in the dialog.

File: packages/desktop-electron/src/main/menu-i18n.ts (hunk 64 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/menu-i18n.ts:15]: Fixed. The comment now states that legacy values were raw locale strings, current values wrap the locale in JSON, and `parseStoredMenuLocale` reads both formats.

File: packages/desktop-electron/src/main/problem-report.ts (hunk 65 above)
Comment (Astro-Han) [reply packages/desktop-electron/src/main/problem-report.ts:176]: Fixed. The truncation comment now explicitly says older entries are dropped first to preserve the most recent context around the failure.

File: packages/app/src/app.tsx [hunk 67]
```diff
@@ -122,13 +125,38 @@ function RouterRoot(props: ParentProps<{ appChildren?: JSX.Element }>) {
...
+    if (!window.api?.setDesktopContext) return
+    if (isSessionRoute(location.pathname)) return
+    void window.api
+      .setDesktopContext(
+        buildDesktopContext({
+          route: `${location.pathname}${location.search}${location.hash}`,
+          locale: language.locale(),
+        }),
+      )
+      .catch(() => undefined)
```
[the remark this answers is not in the document]
Comment (Astro-Han) [reply packages/app/src/app.tsx]: Fixed. The non-session route bridge now uses a bounded retry path with the same retry count and backoff pattern as the session page. Pending retries are cleared when entering a session route or unmounting.

File: packages/app/src/components/settings-general.tsx [hunk 68]
```diff
@@ -114,6 +114,30 @@ export const SettingsGeneral: Component = () => {
...
+            description: language.t("settings.updates.toast.disabled.description"),
+          })
+          return
+        }
+
+        if (result.status === "failed") {
+          showToast({
+            title: language.t("common.requestFailed"),
+            description: result.message ?? language.t("settings.updates.toast.failed.description"),
+          })
```
[the remark this answers is not in the document]
Comment (Astro-Han) [reply packages/app/src/components/settings-general.tsx:137]: Fixed. Failed update toast text now uses a truthy fallback, so an empty message falls back to the localized default description instead of rendering blank feedback.
