### PR TITLE
fix: close opencode upstream intake

### LINKED ISSUE #92: [Feature] Sync OpenCode upstream v1.14.20 intake
## What task are we trying to do?
Sync PawWork's vendored OpenCode foundation from the completed upstream `v1.4.11` cycle to the current upstream release tag `v1.14.20`. `v1.14.20` is now the release anchor for this intake cycle. Keep post-`v1.14.20` fixes as follow-up candidates unless a specific post-tag fix is proven to block macOS or Windows release work.

## What changed since this issue was opened?
Updated 2026-04-22: upstream published `v1.14.20` at 2026-04-21 19:07 UTC, tag commit `3175a3c618` (`release: v1.14.20`). The `v1.14.19..v1.14.20` delta contains 41 commits. Several commits previously listed as post-`v1.14.19` candidates are now release-tagged scope: `92c005866` fixes local dynamic import on Windows and Node by using `file://` URLs; `3406f1874` adds the plugin SDK `env` type; `38e2f4cdd` adds desktop webRequest CORS handling; `91468fe45` and `febadc558` are UI primitive fixes. The delta also includes upstream app UI, TUI, console, web, docs, Nix, debug-server, and experimental HTTP API work that should not automatically enter PawWork's core sync scope.

## What do we do today?
PawWork completed the previous upstream sync cycle at OpenCode `v1.4.11` through scoped squash PRs against `dev`. Current verification on 2026-04-22 shows upstream now publishes `v1.14.20`. PawWork product packages such as `packages/opencode`, `packages/app`, and `packages/desktop-electron` are at `0.2.5`, while upstream-tracked package surfaces such as `packages/plugin`, `packages/function`, `packages/shared`, `packages/ui`, and `packages/sdk/js` are now at `1.14.19` after PR #102. The full upstream tag range `v1.4.11..v1.14.20` reports 149 commits in GitHub compare, but prior PawWork sync PRs have already landed part of that range. Decide remaining work by comparing current code state and behavior, not by upstream commit hash alone.

## What would a good result look like?
Create a new upstream sync cycle that keeps PawWork's existing policy: use graft plus scoped squash merges, do not import upstream contributor history, and do not directly sync `packages/app/src/{components,pages,styles,theme,i18n}/**` because the PawWork app UI rewrite owns that layer. Treat the list below as the candidate intake scope, not literal `git cherry-pick` commands.

## Candidate intake commits
Target release anchor: `v1.14.20` commit `3175a3c618` (`release: v1.14.20`). Treat it as release/version evidence, not as a standalone code candidate.

Base status: PR #102 (`refactor: sync opencode config schemas`) has merged and should be treated as the landed base for config schema, `effect-zod`, OpenAPI metadata, and related type surfaces. If a later lane discovers more base-owned generated/version/dependency work, stop and move it into a small base repair PR before widening that lane.

High-value runtime/session commits: `6f5a3d30f` keeps recent turns during session compaction; `aa86fb75a` refactors compaction tail selection; `9819eb046` changes compaction prune from default-on to explicit opt-in and must be evaluated as part of the prune default sequence; `42771c1db` budgets retained tail with media; `6eddf0824` flips toolcall prune defaults; `b9640fc7e` fixes the compaction prune test to explicitly enable the prune config option; `c6c56ac2c` renames `tail_tokens` to `preserve_recent_tokens` across config, compaction tests, SDK, and OpenAPI; `05cdb7c10` tags session unions and exhaustively matches events, including interleaved tool events, synthetic events, and compaction events; `11cd4fb63` extracts session entry stepping logic; `882b8e1e7` tracks retry attempts with detailed error context on assistant entries; `7a568a457` defers `MessageV2.Assistant.shape` access to break a compiled-binary circular dependency. Also note that `packages/opencode/src/session/system.ts` had no upstream changes in the original `v1.4.11..v1.14.19` scope, so PawWork persona injection should not be a default conflict concern unless a newer diff proves otherwise.

High-value runtime resource commits: `8bc4f91fd` fixes parallel edits sometimes overriding each other; `889087c96` restores the native ripgrep backend; `a7a85c94b` fixes Windows managed ripgrep install behavior and bumps ripgrep to `15.1.0` for ARM64 support; `9918f389e` detects attachment MIME from file contents; `9c16bd1e3` makes skill logic more token efficient; `81b7b58a` handles GitHub Copilot with Haiku where eager input streaming is not supported; `92c005866` fixes local dynamic import on Windows and Node by using `file://` URLs and should move from follow-up to the Runtime Resource lane because it directly affects Windows plugin/tool loading.

NPM/plugin install commits: `1ee712e54` fixes the missing-`node_modules` package install path so it does not continue into dirty-lock checks after install; `f27eb8f09` avoids reinstalling plugins too often by reusing the cached plugin install directory and resolving the entrypoint. Evaluate `e539efe2b` only behind a concrete gate: include it if PawWork's current Bun version reproduces or is confirmed to hit the upstream Arborist/Bun bug, or if the plugin install slice proves it is required. Do not include it merely to match upstream because it adds dependency, lockfile, shared type, and patch-file blast radius.

Config/schema/foundation commits likely needed as dependency chain: `289998481`, `23f31475e`, `2793502db`, `a6a4350d1`, `fc5b35314`, `826fd3350`, `5181f9b4e`, `211136e3a`, `7b98f544f`, `36119ff17`, `bb90f3bbf`, and `1fae784b8`. Because PR #102 already landed, treat this list as historical context plus repair guidance, not as an open instruction to resync those commits from scratch.

Generated output policy: before each slice, decide whether generated files should be taken from upstream blobs or regenerated locally. Do not decide ad hoc inside each slice. If local regeneration is chosen, evaluate `357301991` (`fix(generate): make openapi output deterministic by formatting in-place`) first because it affects OpenAPI/SDK output stability. Generated `chore: generate` commits should be treated as part of their owning functional slice, not as independent product changes.

Desktop-electron commits to evaluate carefully: `e543acf92` bumps Electron and fixes taskbar icon; `b34ca44ab` lazily loads electron-store to fix config directory selection; `a546e88f3` runs JSON migration before spawning the sidecar; `e5687d646` uses custom `oc://` protocol for renderer windows; `eb9906420` enables `contextIsolation` and sandbox; `38e2f4cdd` adds CORS headers to the main window webRequest. These are important for PawWork's macOS and Windows desktop shell, but this lane needs an explicit design note or checklist before intake. The note should map upstream `oc://`, sandbox/contextIsolation, preload/IPC, electron-store config directory, icon/resource generation, and migration order to PawWork's current Electron shell. Do not take `38e2f4cdd` alone without the related protocol/sandbox desktop changes.

Upstream app UI changes in `v1.14.20`: `16caaa2229`, `22d33c57af`, `224548d87d`, `811a7e9a8b`, and `8cc2c81d57` touch upstream app UI behavior such as sidebar avatar fallback, synced project updates, select-server layout, progress-bar setting, and prompt animation. Default skip direct file sync because PawWork's app rewrite owns `packages/app/src/**`. Only convert one into PawWork work if current PawWork behavior shows the same product issue and the fix can be expressed in PawWork's current UI architecture.

Provider/plugin/package commits: `3406f1874` adds an `env` parameter to `WorkspaceAdaptor.create` type; `5eaef6b75` avoids package.json drift during publish; `24fb9b129` stops release publish from rewriting `dev`, and should be evaluated with `5eaef6b75` if upstream publish plumbing stays in scope; release version commits such as `27db54c85`, `7c6948cf6f`, and `3175a3c618` are version evidence, not standalone product changes. Default skip `6e0178655` (NVIDIA provider catalog) unless PawWork explicitly chooses to add NVIDIA as a product/provider decision. Bedrock intake remains optional; if `e2e7a8d72` and `ce7923ada` are included for current upstream Bedrock behavior, include the related `78ca49a1b` Bedrock test fix as well.

UI primitive commits that are safe to evaluate because `packages/ui` is still synced from upstream: `91468fe45` uses `parentID` matching instead of positional scan for assistant messages; `c0eab9e44` adjusts the UI tool diff sticky header offset in `packages/ui/src/components/message-part.tsx`; `febadc558` corrects diff render condition logic. Do not apply upstream `packages/app/src/**` UI changes into PawWork's app rewrite.

TUI policy: PawWork does not keep a TUI product surface. TUI product commits should default to skip. TUI compatibility or tests may be included only when needed to keep shared runtime/session surfaces compiling or tested, or when a slice proves a TUI file is still part of a live package script or import chain. Do not assume PR #73 means all future upstream TUI features remain in scope. `e95474df05` fixes an upstream TUI system-theme regression and adjusts OpenTUI dependency pins; keep it skip-by-default unless a selected runtime/package slice proves the dependency pin change is needed.

New optional or skip-by-default `v1.14.20` candidates: `96a534d8c6` adds `GET /config` to the experimental HTTP API; include only if PawWork desktop/app needs it or if it is required by a selected runtime/API slice. `debcff2b6b` adds a debug workspace server and remains developer tooling, so skip unless we explicitly want that debug workflow. `2486621ca1` removes an unused upstream tool; include only if PawWork's current tool registry still carries that tool and the removal is proven safe with tests. `b5acc2203c` fixes permission routing for remote workspaces; evaluate only if PawWork keeps that shared permission path live outside TUI. `ae7a3518f7`, `ad65af28e7`, `f74a255ca9`, `6278ce51ce`, and related generated commits are console/Zen routing work; skip by default because PawWork's core sync does not include upstream console/web/go surfaces.

## Optional or dependency-only commits
Evaluate `078d8a07c` and `23a2d0128` only if PawWork keeps upstream OpenTelemetry surfaces in scope; they add resource attributes and standardize session telemetry attrs, but PawWork product analytics/crash reporting should remain a separate product decision.

Evaluate `471b9f4dc`, `1dd257b76`, `5fa167334`, `e6fd57165`, and `a5d99e7a3` only as dependency-chain commits or if they prevent concrete ambient-instance bugs while applying later changes. They move worktree, MCP, provider, file, LSP, and formatter code toward explicit `InstanceState` context, but they are mostly architecture cleanup.

## Non-goals and carve-outs
Do not directly sync upstream `packages/app/src/{components,pages,styles,theme,i18n}/**`. Keep PawWork-only differences such as `packages/opencode/src/tool/trash.ts`, `packages/opencode/test/tool/trash.test.ts`, `packages/opencode/src/session/prompt/pawwork-persona.txt`, and `packages/opencode/src/provider/models-snapshot.js` unless a later review proves a specific change is required.

Do not preserve upstream commit history inside PawWork. The commit list above is for scope analysis and review planning only. Because prior PawWork sync work used squash merges, do not decide whether a candidate is already present by upstream commit hash alone; compare current code state or behavior when needed.

## Suggested execution plan
This replaces the earlier 5-slice execution plan. Keep the candidate commit sections above as the analysis index, but execute through the landed base, three lanes, and one optional tail.

Phase 0 Base PR: mostly landed through PR #102. Own config schema, effect-zod, SDK/OpenAPI, package/version surfaces, generated output policy, and any dependency/lockfile changes that later lanes need. If a remaining task needs to change Base-owned surfaces, use a small base repair PR instead of hiding it inside a later lane.

Phase 1 Session lane: can start after Base. Own session runtime, v2 event matching, compaction behavior, and the compaction prune default/test sequence. Keep this lane internally coherent because the compaction commits depend on each other.

Phase 1 Runtime Resource lane: can start after Base and run in parallel with Session and Desktop. Own tool/file behavior, parallel edit safety, read/media MIME handling, ripgrep backend, Windows managed ripgrep install support, local dynamic import on Windows/Node, skill token efficiency, npm/plugin install behavior, plugin cache reuse, and missing-`node_modules` handling.

Phase 1 Desktop lane: can prepare the design note/checklist in parallel immediately, then implement after Base. Own Electron shell changes, `oc://`, sandbox/contextIsolation, preload/IPC, electron-store config directory, icon/resource generation, migration order, and macOS/Windows desktop smoke coverage.

Phase 2 Optional tail: open only if a concrete product or release decision accepts the work. This covers upstream `packages/ui` primitives, optional Bedrock, optional publish plumbing, selected app-UI behavior reimplemented in PawWork architecture, and explicitly chosen provider catalog changes. Default skip NVIDIA provider catalog. Keep this tail out of the core sync path unless it becomes a blocker.

Parallelization rule: Phase 1 lanes should branch from the Base PR result, not from stale `dev`, to avoid repeated generated/schema conflicts. If a lane discovers it needs to touch Base-owned files, stop and either move that change back into Base or re-scope the lane before continuing.

## Verification notes
Before implementation, refresh upstream with `git fetch --no-tags upstream` and resolve the exact target refs again. After each slice, run focused tests for the touched package, then at minimum run the repo's normal lint/typecheck path for the touched surfaces. For desktop-electron changes, include macOS and Windows desktop smoke coverage because context isolation, sandbox, protocol, CORS handling, and migration order are startup and packaging risks on both platforms.

### PR DESCRIPTION
**Pull request by Astro-Han**
## Summary

- Add content-based attachment MIME sniffing so `read` promotes disguised image/PDF files while keeping SVG/text paths readable.
- Sync the remaining upstream runtime/plugin tail: GitHub Copilot Anthropic tool streaming opt-out, workspace adaptor env propagation, and skill discovery abort handling.
- Port the small UI primitive fixes for assistant parent lookup, review diff renderability, and tool accordion sticky offsets.

## Why

This is the final scoped #92 closeout after the session runtime lane in #140 landed. Desktop hardening remains tracked separately in #141/#152 and is not blocking this upstream intake closeout.

## Related Issue

Closes #92

## How To Verify

```bash
cd packages/opencode
bun test test/tool/read.test.ts test/session/message-v2.test.ts test/plugin/github-copilot-models.test.ts test/plugin/workspace-adaptor.test.ts
cd ../ui
bun test src/components/message-part-stale.test.ts src/components/session-turn-parent.test.ts src/components/session-review-diff-render.test.ts
cd ../..
bun turbo typecheck
bun turbo test:ci
git diff --check
```

## Screenshots or Recordings

Not applicable. The UI changes are narrow primitive guards and sticky offset constants covered by focused source tests plus the app build in `test:ci`.

## Checklist

- [x] I linked the related issue, or stated why there is no issue
- [x] This PR has type, scope, and priority labels, or I requested maintainer labeling
- [x] I listed the relevant verification steps, including tests when behavior changed
- [x] I manually checked visible UI or copy changes when needed, with screenshots or recordings
- [x] I considered macOS and Windows impact for desktop, packaging, updater, signing, paths, shell, or permissions changes
- [x] I called out docs, release notes, dependencies, permissions, credentials, deletion behavior, or generated/local file changes when relevant
- [x] I am targeting `dev`, and my PR title and commit messages use Conventional Commits in English

## Summary by CodeRabbit

* **Bug Fixes**
  * Copilot behavior: correct handling for Anthropic-backed models and headers
  * Sticky accordion offset alignment in UI components
  * Session review diff visibility and per-file interaction states
  * Assistant threading now includes relevant follow-up assistant messages

* **Improvements**
  * Improved media/attachment detection via file-signature sniffing and stricter binary checks
  * Safer PDF/image handling with size caps and proper data-URL responses
  * Workspace creation now propagates runtime environment (auth, workspace id, OTEL) to spawned processes
  * File discovery respects cancellation for faster aborts

* **Tests**
  * New tests for Copilot model behavior, media sniffing, workspace env propagation, and session/message handling

### CODE REVIEW

File: packages/opencode/src/control-plane/workspace.ts [hunk 1]
```diff
@@ -200,7 +202,15 @@ export namespace Workspace {
         .run()
     })
 
-    await adaptor.create(config)
+    const env = {
+      OPENCODE_AUTH_CONTENT: JSON.stringify(await AppRuntime.runPromise(Auth.Service.use((auth) => auth.all()))),
```
Comment (Astro-Han) [inline packages/opencode/src/control-plane/workspace.ts]: **[P1][security-ish]** `OPENCODE_AUTH_CONTENT` serializes **every** provider's auth blob into an env var handed to whatever adaptor is registered — including third-party plugin adaptors the user may have installed for unrelated reasons. There is no per-provider scoping and no opt-in from the adaptor side; a plugin author who only wanted to implement `create(config)` now transparently receives every credential.

At minimum: document this on the `WorkspaceAdaptor.create` contract in `packages/plugin/src/index.ts` so plugin authors know what they're being handed. Ideally, narrow the blob to the auth entries relevant to `config` (or the currently selected provider), or require adaptors to opt in via a separate parameter shape. This keeps the blast radius of a compromised/curious plugin bounded.

File: packages/opencode/src/control-plane/workspace.ts [hunk 2]
```diff
@@ -200,7 +202,15 @@ export namespace Workspace {
...
+      OPENCODE_WORKSPACE_ID: config.id,
+      OPENCODE_EXPERIMENTAL_WORKSPACES: "true",
+      OTEL_EXPORTER_OTLP_HEADERS: process.env.OTEL_EXPORTER_OTLP_HEADERS,
+      OTEL_EXPORTER_OTLP_ENDPOINT: process.env.OTEL_EXPORTER_OTLP_ENDPOINT,
+      OTEL_RESOURCE_ATTRIBUTES: process.env.OTEL_RESOURCE_ATTRIBUTES,
```
Comment (Astro-Han) [inline packages/opencode/src/control-plane/workspace.ts]: **[P2]** `Record<string, string | undefined>` leaks OTEL env variables through even when they're `undefined` in the parent process. Most adaptors will forward this straight to `child_process.spawn({ env })`, and Node's behavior for `undefined` env values is version-dependent (some stringify to `"undefined"`, some drop the key). Cleaner to filter undefineds at the boundary:

```ts
const env = Object.fromEntries(
  Object.entries({
    OPENCODE_AUTH_CONTENT: ...,
    OPENCODE_WORKSPACE_ID: config.id,
    OPENCODE_EXPERIMENTAL_WORKSPACES: "true",
    OTEL_EXPORTER_OTLP_HEADERS: process.env.OTEL_EXPORTER_OTLP_HEADERS,
    OTEL_EXPORTER_OTLP_ENDPOINT: process.env.OTEL_EXPORTER_OTLP_ENDPOINT,
    OTEL_RESOURCE_ATTRIBUTES: process.env.OTEL_RESOURCE_ATTRIBUTES,
  }).filter(([, v]) => v !== undefined),
) as Record<string, string>
```

This also lets the plugin API type `env` as `Record<string, string>` — a nicer contract for adaptor authors.

File: packages/plugin/src/index.ts [hunk 3]
```diff
@@ -49,7 +49,7 @@ export type WorkspaceAdaptor = {
   name: string
   description: string
   configure(config: WorkspaceInfo): WorkspaceInfo | Promise<WorkspaceInfo>
-  create(config: WorkspaceInfo, from?: WorkspaceInfo): Promise<void>
+  create(config: WorkspaceInfo, env: Record<string, string | undefined>, from?: WorkspaceInfo): Promise<void>
```
Comment (Astro-Han) [inline packages/plugin/src/index.ts]: **[P2][API-compat]** This is a hard-breaking TypeScript signature change on the exported `WorkspaceAdaptor.create`. Any plugin consumer that previously typed their adaptor as `create(config)` will fail `strict`/`noImplicitAny` compilation against the new `@opencode-ai/plugin` release — note that even the in-repo `packages/plugin/src/example-workspace.ts` still uses the one-arg form and happens to work only because TS allows omitting trailing parameters at the call site.

Either: (a) call it out in release notes for the plugin package, (b) make `env` optional (`env?:`) so existing adaptors keep compiling, or (c) ship a migration note in the plugin README.

File: packages/ui/src/components/session-review.tsx [hunk 4]
```diff
@@ -493,16 +493,18 @@ export const SessionReview = (props: SessionReviewProps) => {
                       commentsUi.onLineSelectionEnd(range)
                     }
 
+                    const diffCanRender = () => diff.additions !== 0 || diff.deletions !== 0
+
                     return (
                       <Accordion.Item
-                        value={file}
+                        value={diffCanRender() ? file : null!}
```
Comment (Astro-Han) [inline packages/ui/src/components/session-review.tsx]: **[P1]** `value={diffCanRender() ? file : null!}` uses the non-null-assertion operator to lie to TypeScript. At runtime Kobalte's `Accordion.Item` receives `null` as its value — and if a review contains two zero-diff files (e.g. both renamed, or both metadata-only), **they now share the same `null` key** and the accordion's internal selection map can't tell them apart. A `multiple`-mode accordion with duplicate values tends to open/close them in lockstep.

Safer to keep the unique `file` value on every item and rely on `disabled={!diffCanRender()}` alone (you already do, two lines below), or split the zero-diff case into a plain non-accordion row rendered as a sibling.

File: packages/ui/src/components/session-review.tsx [hunk 5]
```diff
@@ -493,16 +493,18 @@ export const SessionReview = (props: SessionReviewProps) => {
...
                         id={diffId(file)}
                         data-file={file}
                         data-slot="session-review-accordion-item"
                         data-selected={props.focusedFile === file ? "" : undefined}
                       >
                         <StickyAccordionHeader>
-                          <Accordion.Trigger>
+                          <Accordion.Trigger disabled={!diffCanRender()} class="cursor-default">
```
Comment (Astro-Han) [inline packages/ui/src/components/session-review.tsx]: **[P2]** `disabled={!diffCanRender()} class="cursor-default"` gives off a mixed signal: the control is disabled, but the cursor says "nothing special, go ahead." Native disabled state is `cursor: not-allowed`; overriding it to `default` usually means the author didn't actually want `disabled` semantics (e.g. they want the row to look normal but be inert). Either:

- Drop the cursor override and let the standard disabled cursor show, or
- Replace `disabled` with `aria-disabled="true"` + a no-op click handler, keeping the appearance you want without confusing assistive tech.

Minor, but worth picking one.

File: packages/ui/src/components/session-turn.tsx [hunk 6]
```diff
@@ -267,17 +267,9 @@ export function SessionTurn(
...
-      for (let i = index + 1; i < messages.length; i++) {
-        const item = messages[i]
-        if (!item) continue
-        if (item.role === "user") break
-        if (item.role === "assistant" && item.parentID === msg.id) result.push(item as AssistantMessage)
-      }
-      return result
+      if (messageIndex() < 0) return emptyAssistant
+
+      return messages.filter((item): item is AssistantMessage => item.role === "assistant" && item.parentID === msg.id)
```
Comment (Astro-Han) [inline packages/ui/src/components/session-turn.tsx]: **[P2][perf/correctness trade-off]** The old scan was `O(turn-length)` with a hard stop at the next `user` message. This rewrite is `O(N)` over the entire `messages` array, per `createMemo` recomputation, across every turn — for a long session (say, 300 messages across 10 turns) the sum of work is quadratic in turn count.

The fix is correct in intent (the old boundary missed valid `parentID` matches). But two questions worth confirming before accepting the unbounded scan:

1. Is `parentID` guaranteed to point to the `msg.id` that is *earlier* in the list? If so, starting the scan at `messageIndex() + 1` is still correct and keeps the optimization.
2. If assistant messages *can* arrive after the next user turn, under what condition? A short comment here would save the next maintainer from re-deriving this on sight of a hot-path profile.

One-line fix if (1) holds:

```ts
return messages.slice(messageIndex() + 1).filter(
  (item): item is AssistantMessage => item.role === "assistant" && item.parentID === msg.id,
)
```

File: packages/opencode/src/tool/read.ts [hunk 7]
```diff
@@ -142,9 +155,10 @@ export const ReadTool = Tool.define(
 
       const loaded = yield* instruction.resolve(ctx.messages, filepath, ctx.messageID)
 
-      const mime = AppFileSystem.mimeType(filepath)
-      const isImage = mime.startsWith("image/") && mime !== "image/svg+xml" && mime !== "image/vnd.fastbidsheet"
-      const isPdf = mime === "application/pdf"
+      const sample = yield* readSample(filepath, Number(stat.size))
```
Comment (Astro-Han) [inline packages/opencode/src/tool/read.ts:166]: **[P2]** `readSample` now runs unconditionally, *before* the extension-based binary short-circuit inside `isBinaryFile`. For any file with a known-binary extension (`.zip`, `.exe`, `.so`, `.class`, etc.), we still pay 4 KB of disk I/O for a sniff whose result is never consumed — the `isBinary` path returns early, and the attachment path is unreachable because none of the magic-byte signatures overlap with those extensions.

Either:

- Move the extension switch out of `isBinaryFile` into a separate `isBinaryByExt(filepath)` and short-circuit before `readSample`, or
- Accept the minor regression and add a comment that the sample is unconditional for simplicity.

Not worth blocking on, but cheap to fix.

File: packages/opencode/src/plugin/github-copilot/copilot.ts [hunk 8]
```diff
@@ -334,6 +334,9 @@ export async function CopilotAuthPlugin(input: PluginInput): Promise<Hooks> {
       if (incoming.model.api.id.includes("gpt")) {
         output.maxOutputTokens = undefined
       }
+      if (incoming.model.api.npm === "@ai-sdk/anthropic") {
+        output.options.toolStreaming = false
```
Comment (Astro-Han) [inline packages/opencode/src/plugin/github-copilot/copilot.ts:342]: **[P2]** `@ai-sdk/anthropic` is hardcoded in a plain branch right next to another `incoming.model.api.npm === "@ai-sdk/anthropic"` check in `chat.headers` (line 344). If a future Copilot npm adapter also needs tool-streaming disabled (history suggests `@ai-sdk/google` and friends have had similar quirks), this will silently regress.

Two cheap hardens:

1. Lift a `const isCopilotAnthropic = incoming.model.api.npm === "@ai-sdk/anthropic"` to the top and reuse it in both hooks.
2. Add a one-line anchor comment explaining **why** tool streaming is disabled (Copilot proxy stripping stream chunks? SDK bug?) — the next maintainer will thank you when deciding whether to remove the workaround.

File: packages/opencode/src/util/media.ts [hunk 9]
```diff
@@ -0,0 +1,28 @@
...
+  if (startsWith(bytes, [0xff, 0xd8, 0xff])) return "image/jpeg"
+  if (startsWith(bytes, [0x47, 0x49, 0x46, 0x38])) return "image/gif"
+  if (startsWith(bytes, [0x42, 0x4d])) return "image/bmp"
+  if (startsWith(bytes, [0x25, 0x50, 0x44, 0x46, 0x2d])) return "application/pdf"
+  if (
+    startsWith(bytes, [0x52, 0x49, 0x46, 0x46]) &&
+    bytes.length >= 12 &&
+    startsWith(bytes.slice(8, 12), [0x57, 0x45, 0x42, 0x50])
+  )
+    return "image/webp"
```
Comment (Astro-Han) [inline packages/opencode/src/util/media.ts:37]: **[P3]** The PR stated goal is to promote "disguised image/PDF files." The signature list covers PNG/JPEG/GIF/BMP/PDF/WebP, but skips three formats that are extremely common on modern devices:

- **TIFF**: `49 49 2A 00` (little-endian) / `4D 4D 00 2A` (big-endian)
- **HEIC / HEIF**: `....ftypheic` / `ftyphevc` at offset 4
- **AVIF**: `....ftypavif` at offset 4

If a user drags a renamed `.heic` off an iPhone today, the sniff returns the fallback mime (often `application/octet-stream`), the attachment path doesn't trigger, and the file hits `isBinaryFile` and fails. Either add these signatures or note the supported set in a comment so the gap is explicit.

File: packages/opencode/test/plugin/workspace-adaptor.test.ts [hunk 10]
```diff
@@ -141,13 +141,17 @@ describe("plugin.workspace", () => {
...
+    expect(created.input).toMatchObject({
       type: tmp.extra.type,
       name: "plug",
       branch: "plug/main",
       directory: tmp.extra.space,
       extra: { key: "value" },
     })
+    expect(created.env.OPENCODE_WORKSPACE_ID).toBe(info.id)
+    expect(created.env.OPENCODE_EXPERIMENTAL_WORKSPACES).toBe("true")
+    expect(JSON.parse(created.env.OPENCODE_AUTH_CONTENT)).toEqual({})
```
Comment (Astro-Han) [inline packages/opencode/test/plugin/workspace-adaptor.test.ts]: **[P3]** `toEqual({})` asserts the test runtime has **zero** auth entries. The moment another test helper (or a future `beforeAll`) seeds an auth fixture, this explodes without telling the reader what the meaningful contract is. Prefer a shape assertion:

```ts
const auth = JSON.parse(created.env.OPENCODE_AUTH_CONTENT)
expect(typeof auth).toBe("object")
expect(auth).not.toBeNull()
```

Or if the intent is "env-propagated auth is whatever `auth.all()` returned at the time," call `Auth.Service.use(a => a.all())` inside the test and compare against that.

File: packages/ui/src/components/session-turn-parent.test.ts [hunk 11]
```diff
@@ -0,0 +1,12 @@
+import { expect, test } from "bun:test"
```
Comment (Astro-Han) [inline packages/ui/src/components/session-turn-parent.test.ts:1]: **[P3][test-quality]** This (and `session-review-diff-render.test.ts`, and the new case added to `message-part-stale.test.ts`) asserts against `readFileSync`'d source strings. That's fine as a regression pin for a specific refactor, but each new source-match test compounds the tax: any stylistic refactor (line-wrapping, variable renames, even `const` → `let`) breaks the test without flagging a real regression, and no real regression in the `parentID` lookup logic would be caught by a substring check.

Not blocking — the pattern is already established in this directory — but a thin render test via `@solidjs/testing-library` that mounts `SessionTurn` with a crafted `allMessages()` and asserts the returned `assistantMessages` signal would actually defend the invariant.

**Review by Astro-Han — COMMENTED** [review]
Nitpicky review of the upstream-intake closeout. Findings labeled P0–P3; nothing looks blocking for the stated scope, but a few of the P1/P2 items (auth env fanout, `null!` on Accordion.Item, and the unbounded turn scan) feel worth a second look before merge.

- P1: 3
- P2: 4
- P3: 3

File: packages/opencode/src/control-plane/workspace.ts (hunk 1 above)
Comment (Astro-Han) [reply packages/opencode/src/control-plane/workspace.ts]: Documented the workspace adaptor env contract in packages/plugin/src/index.ts, including that OPENCODE_AUTH_CONTENT is a serialized provider auth blob and must be treated as secret. I did not narrow the auth blob in this PR because WorkspaceInfo does not carry provider selection, so that would be a separate plugin contract change rather than a safe #92 tail fix.

File: packages/opencode/src/control-plane/workspace.ts (hunk 2 above)
Comment (Astro-Han) [reply packages/opencode/src/control-plane/workspace.ts]: Fixed. The env object now filters undefined values at the boundary and is typed as Record<string, string>.

File: packages/plugin/src/index.ts (hunk 3 above)
Comment (Astro-Han) [reply packages/plugin/src/index.ts]: Fixed. The plugin API now makes env optional and documents the secret-bearing env contract, so existing one-argument adaptors continue to type cleanly.

File: packages/ui/src/components/session-review.tsx (hunk 4 above)
Comment (Astro-Han) [reply packages/ui/src/components/session-review.tsx]: Fixed. Accordion.Item now keeps value={file} for every row and relies on the disabled trigger for non-renderable diffs, avoiding duplicate null values.

File: packages/ui/src/components/session-review.tsx (hunk 5 above)
Comment (Astro-Han) [reply packages/ui/src/components/session-review.tsx]: Fixed. Removed the cursor override and kept native disabled semantics.

File: packages/ui/src/components/session-turn.tsx (hunk 6 above)
Comment (Astro-Han) [reply packages/ui/src/components/session-turn.tsx]: Fixed. The lookup now starts at messageIndex() + 1 and still filters by parentID, with a short comment explaining why it no longer stops at the next user message.

File: packages/opencode/src/tool/read.ts (hunk 7 above)
Comment (Astro-Han) [reply packages/opencode/src/tool/read.ts:166]: Fixed. Split extension-based binary detection out and short-circuit known binary extensions before sampling, while still allowing .bin and .dat to be sniffed for disguised image/PDF attachments before rejecting them as binary.

File: packages/opencode/src/plugin/github-copilot/copilot.ts (hunk 8 above)
Comment (Astro-Han) [reply packages/opencode/src/plugin/github-copilot/copilot.ts:342]: Fixed. Reused an isCopilotAnthropic local in both hooks and added the upstream reason: Copilot's messages shim rejects the eager_input_streaming field injected by @ai-sdk/anthropic tool streaming.

File: packages/opencode/src/util/media.ts (hunk 9 above)
Comment (Astro-Han) [reply packages/opencode/src/util/media.ts:37]: Fixed. Added TIFF, HEIC, and AVIF content sniffing plus coverage for renamed .bin/.dat files.

File: packages/opencode/test/plugin/workspace-adaptor.test.ts (hunk 10 above)
Comment (Astro-Han) [reply packages/opencode/test/plugin/workspace-adaptor.test.ts]: Fixed. The test now checks OPENCODE_AUTH_CONTENT as a non-null object shape instead of assuming the auth store is empty, and verifies exported env values are strings.

File: packages/ui/src/components/session-turn-parent.test.ts (hunk 11 above)
Comment (Astro-Han) [reply packages/ui/src/components/session-turn-parent.test.ts:1]: Leaving this as a source-level regression pin for this PR. This directory already uses that lightweight pattern, and adding a Solid render harness would be larger than the #92 closeout tail. I did tighten the source assertion to cover the new slice-based parentID invariant.

**Comment by Astro-Han** [comment]
@coderabbitai review

File: packages/opencode/src/util/media.ts [hunk 12]
```diff
@@ -0,0 +1,37 @@
...
+  if (startsWithAt(bytes, 4, ascii("ftyp"))) {
+    if (startsWithAt(bytes, 8, ascii("avif"))) return "image/avif"
+    if (startsWithAt(bytes, 8, ascii("heic")) || startsWithAt(bytes, 8, ascii("hevc"))) return "image/heic"
+  }
```
[the remark this answers is not in the document]
Comment (Astro-Han) [reply packages/opencode/src/util/media.ts:47]: Fixed. The ftyp sniff now reads the box size and scans all 4-byte brand entries in the box, so compatible-brand-only HEIF/AVIF files are detected. Added regression coverage for isom major brand files that advertise heix, hevx, or avis only in the compatible brand list.

File: packages/opencode/src/util/media.ts [hunk 13]
```diff
@@ -0,0 +1,48 @@
+const startsWith = (bytes: Uint8Array, prefix: number[]) => prefix.every((value, index) => bytes[index] === value)
```
Comment (Astro-Han) [inline packages/opencode/src/util/media.ts]: test comment - please ignore

File: packages/opencode/src/control-plane/types.ts [hunk 14]
```diff
@@ -26,7 +26,7 @@ export type Target =
 
 export type Adaptor = {
   configure(input: WorkspaceInfo): WorkspaceInfo | Promise<WorkspaceInfo>
-  create(config: WorkspaceInfo, from?: WorkspaceInfo): Promise<void>
+  create(config: WorkspaceInfo, env?: Record<string, string>, from?: WorkspaceInfo): Promise<void>
```
Comment (Astro-Han) [inline packages/opencode/src/control-plane/types.ts:30]: **[P2][dead param]** The `from?` parameter on `Adaptor.create` is never wired up — `workspace.ts` calls `adaptor.create(config, env)` with no third argument. This was dead code before this PR and still is. Either remove `from?` from both `Adaptor` and `WorkspaceAdaptor` (they're in lockstep), or add a `// TODO: reserved for future use` so adaptor authors don't wonder what to do with it.

File: packages/opencode/src/control-plane/workspace.ts [hunk 15]
```diff
@@ -200,7 +204,17 @@ export namespace Workspace {
         .run()
     })
 
-    await adaptor.create(config)
+    const env = Object.fromEntries(
+      Object.entries({
+        OPENCODE_AUTH_CONTENT: JSON.stringify(await AppRuntime.runPromise(Auth.Service.use((auth) => auth.all()))),
```
Comment (Astro-Han) [inline packages/opencode/src/control-plane/workspace.ts:209]: **[P1][security re-raise]** The previous review noted that `OPENCODE_AUTH_CONTENT` serializes *all* provider credentials into an env var. The fix was doc-only (JSDoc on `WorkspaceAdaptor.create`). Re-raising because the blast radius is credential exposure to untrusted plugin code — documentation is advisory, not enforceable. Consider scoping to only the auth entries relevant to `config.type`'s provider, or logging a one-time warning when a non-builtin adaptor receives `OPENCODE_AUTH_CONTENT`. At minimum, track as a follow-up issue so it doesn't get lost after merge.

File: packages/opencode/src/util/media.ts (hunk 13 above)
Comment (Astro-Han) [inline packages/opencode/src/util/media.ts]: **[P1][crash risk]** `startsWith` does not bounds-check `bytes.length` against `prefix.length`. `startsWithAt` (line 2) checks `bytes.length >= offset + prefix.length` but `startsWith` doesn't. If a future caller passes a sample shorter than the prefix, `bytes[index]` reads `undefined` and silently returns `false` — no error, just a wrong result. The asymmetry is a landmine. Fix:

```ts
const startsWith = (bytes: Uint8Array, prefix: number[]) =>
  bytes.length >= prefix.length && prefix.every((value, index) => bytes[index] === value)
```

File: packages/opencode/src/util/media.ts [hunk 16]
```diff
@@ -0,0 +1,48 @@
...
+  if (startsWith(bytes, [0x25, 0x50, 0x44, 0x46, 0x2d])) return "application/pdf"
+  if (
+    startsWith(bytes, [0x52, 0x49, 0x46, 0x46]) &&
+    bytes.length >= 12 &&
+    startsWith(bytes.slice(8, 12), [0x57, 0x45, 0x42, 0x50])
+  )
+    return "image/webp"
+  if (startsWithAt(bytes, 4, ascii("ftyp"))) {
+    const boxSize = u32be(bytes, 0)
+    const limit = Math.min(boxSize || bytes.length, bytes.length)
```
Comment (Astro-Han) [inline packages/opencode/src/util/media.ts]: **[P2][subtle bug]** `boxSize || bytes.length` — if `u32be` returns `0` (sample too short for the box-size field), `0 || bytes.length` falls through to `bytes.length`, which happens to be correct. But a genuine `boxSize` of 0 (degenerate but per ISO 14496-12 not forbidden) would also fall through, scanning the entire sample as brands. Use `boxSize > 0 ? boxSize : bytes.length` or add a comment explaining the `0` fallback.

File: packages/opencode/src/plugin/github-copilot/copilot.ts [hunk 17]
```diff
@@ -329,16 +329,23 @@ export async function CopilotAuthPlugin(input: PluginInput): Promise<Hooks> {
...
       }
+
+      // Copilot's /v1/messages shim rejects the eager_input_streaming field.
+      if (isCopilotAnthropic) {
+        output.options.toolStreaming = false
+      }
     },
     "chat.headers": async (incoming, output) => {
       if (!incoming.model.providerID.includes("github-copilot")) return
+      const isCopilotAnthropic = incoming.model.api.npm === "@ai-sdk/anthropic"
```
Comment (Astro-Han) [inline packages/opencode/src/plugin/github-copilot/copilot.ts]: **[P3][DRY]** `isCopilotAnthropic` is computed independently in `chat.params` (line 332) and `chat.headers` (line 346). The string `"@ai-sdk/anthropic"` is duplicated. If Copilot adds a second Anthropic npm adapter, both hooks need updating. Extract a `const COPILOT_ANTHROPIC_NPM = "@ai-sdk/anthropic"` at the top of the plugin.

File: packages/opencode/test/plugin/github-copilot-models.test.ts [hunk 18]
```diff
@@ -161,3 +161,31 @@ test("remaps fallback oauth model urls to the enterprise host", async () => {
   expect(models.claude.api.url).toBe("https://copilot-api.ghe.example.com")
   expect(models.claude.api.npm).toBe("@ai-sdk/github-copilot")
 })
+
+test("disables anthropic tool streaming for github copilot chat params", async () => {
```
Comment (Astro-Han) [inline packages/opencode/test/plugin/github-copilot-models.test.ts:165]: **[P2][test gap]** This test only verifies the positive case (Copilot + Anthropic -> toolStreaming: false). Missing:

1. **Non-Anthropic Copilot model** (e.g. `api.npm = "@ai-sdk/openai"`) should *not* set `toolStreaming: false`.
2. **Non-Copilot Anthropic model** (e.g. `providerID: "anthropic"`) should also *not* set it.

At least one negative case is needed to lock in the AND condition.

File: packages/opencode/test/tool/read.test.ts [hunk 19]
```diff
@@ -421,6 +427,80 @@ describe("tool.read truncation", () => {
...
+      expect(result.output).toContain("PDF read successfully")
+      expect(result.attachments?.[0]?.mime).toBe("application/pdf")
+      expect(result.attachments?.[0]?.url).toStartWith("data:application/pdf;base64,")
+    }),
+  )
+
+  it.live("detects modern image attachment media from file contents", () =>
+    Effect.gen(function* () {
+      const dir = yield* tmpdirScoped()
+      yield* put(path.join(dir, "photo.bin"), Buffer.from([0x49, 0x49, 0x2a, 0x00]))
```
Comment (Astro-Han) [inline packages/opencode/test/tool/read.test.ts]: **[P2][test gap]** The TIFF fixture is only 4 bytes. Too small to exercise the full attachment path (base64 encoding, data URL construction). Pad to 8+ bytes to exercise `readSample`'s `Math.min(SAMPLE_BYTES, fileSize)` more realistically.

File: packages/opencode/test/plugin/workspace-adaptor.test.ts [hunk 20]
```diff
@@ -141,13 +141,22 @@ describe("plugin.workspace", () => {
     expect(info.branch).toBe("plug/main")
     expect(info.directory).toBe(tmp.extra.space)
     expect(info.extra).toEqual({ key: "value" })
-    expect(JSON.parse(await Bun.file(tmp.extra.mark).text())).toMatchObject({
+    const created = JSON.parse(await Bun.file(tmp.extra.mark).text())
+    expect(created.input).toMatchObject({
       type: tmp.extra.type,
       name: "plug",
       branch: "plug/main",
```
Comment (Astro-Han) [inline packages/opencode/test/plugin/workspace-adaptor.test.ts:148]: **[P3][fragile]** `for (const value of Object.values(created.env))` asserts all env values are strings. But `OPENCODE_AUTH_CONTENT` is `JSON.stringify(...)` by construction. The interesting invariant is that OTEL keys are *absent* when not set. Consider asserting key absence instead, or remove the noise.

File: packages/opencode/src/tool/read.ts [hunk 21]
```diff
@@ -142,9 +155,14 @@ export const ReadTool = Tool.define(
 
       const loaded = yield* instruction.resolve(ctx.messages, filepath, ctx.messageID)
 
-      const mime = AppFileSystem.mimeType(filepath)
-      const isImage = mime.startsWith("image/") && mime !== "image/svg+xml" && mime !== "image/vnd.fastbidsheet"
-      const isPdf = mime === "application/pdf"
+      if (isBinaryByExt(filepath) && !shouldSniffBeforeBinaryExt(filepath)) {
```
Comment (Astro-Han) [inline packages/opencode/src/tool/read.ts:160]: **[P2][UX]** Before this PR, a binary-extension file would still get content-sampled by `isBinaryFile`'s byte heuristic. Now `isBinaryByExt` short-circuits with an error. The message `"Cannot read binary file"` is identical to the content-detected one (line 186). A user can't tell whether rejection was due to extension or content. Consider differentiating: `"Cannot read binary file (extension: .zip)"` vs `"Cannot read binary file (content inspection)"`.

File: packages/opencode/src/tool/read.ts [hunk 22]
```diff
@@ -142,9 +155,14 @@ export const ReadTool = Tool.define(
...
+        return yield* Effect.fail(new Error(`Cannot read binary file: ${filepath}`))
+      }
+
+      const sample = yield* readSample(filepath, Number(stat.size))
```
Comment (Astro-Han) [inline packages/opencode/src/tool/read.ts:166]: **[P1][memory]** When a sniffed image/PDF is detected, `readSample` just read 4 KB into `sample`, then `fs.readFile(filepath)` at line 180 reads the *entire file* to base64-encode it. For large files (e.g. a 20 MB RAW photo renamed to `.bin`), the full content is held multiple times in the JS heap (readSample Uint8Array + readFile Buffer + base64 string). The `sample` variable is unused after `sniffAttachmentMime` returns — consider scoping it for GC, or add a comment.

Also: **no file-size cap** on image/PDF attachments. A 100 MB PDF will be eagerly base64-encoded into a data URL, likely OOMing. Consider adding `MAX_ATTACHMENT_BYTES` before the readFile at line 180.

File: packages/opencode/src/tool/read.ts [hunk 23]
```diff
@@ -262,7 +280,28 @@ async function lines(filepath: string, opts: { limit: number; offset: number })
...
+    if (sample[i] === 0) return true
+    if (sample[i] < 9 || (sample[i] > 13 && sample[i] < 32)) {
+      nonPrintableCount++
+    }
+  }
+  // If >30% non-printable characters, consider it binary
+  return nonPrintableCount / sample.byteLength > 0.3
+}
+
+function shouldSniffBeforeBinaryExt(filepath: string): boolean {
```
Comment (Astro-Han) [inline packages/opencode/src/tool/read.ts:309]: **[P3][coupling]** `shouldSniffBeforeBinaryExt` allows `.bin` and `.dat` to bypass the extension short-circuit. But those extensions are *also* in `isBinaryByExt`'s switch (lines 337-338). The two lists must stay in sync: if someone adds to `shouldSniffBeforeBinaryExt` but forgets `isBinaryByExt`, the sniff-override becomes dead code. A comment explaining the coupling would help.

File: packages/opencode/src/util/media.ts (hunk 13 above)
Comment (Astro-Han) [reply packages/opencode/src/util/media.ts]: Ignored as requested.

File: packages/opencode/src/control-plane/types.ts (hunk 14 above)
Comment (Astro-Han) [reply packages/opencode/src/control-plane/types.ts:30]: Handled with a reserved-for-future-use comment on both the internal Adaptor.create and public WorkspaceAdaptor.create contracts. I kept the parameter for compatibility instead of removing it in this PR.

File: packages/opencode/src/control-plane/workspace.ts (hunk 15 above)
Comment (Astro-Han) [reply packages/opencode/src/control-plane/workspace.ts:209]: Not changing auth scoping in #155 because WorkspaceInfo does not carry provider selection, and narrowing or opt-in would be a separate plugin contract design. Created follow-up #173 to track scoped or opt-in OPENCODE_AUTH_CONTENT propagation.

File: packages/opencode/src/util/media.ts (hunk 13 above)
Comment (Astro-Han) [reply packages/opencode/src/util/media.ts]: Fixed. startsWith now checks bytes.length before comparing the prefix.

File: packages/opencode/src/util/media.ts (hunk 16 above)
Comment (Astro-Han) [reply packages/opencode/src/util/media.ts]: Fixed. The ftyp box limit now uses boxSize > 0 ? boxSize : bytes.length so the zero-size fallback is explicit.

File: packages/opencode/src/plugin/github-copilot/copilot.ts (hunk 17 above)
Comment (Astro-Han) [reply packages/opencode/src/plugin/github-copilot/copilot.ts]: Fixed. Extracted COPILOT_ANTHROPIC_NPM and reused it in both hooks.

File: packages/opencode/test/plugin/github-copilot-models.test.ts (hunk 18 above)
Comment (Astro-Han) [reply packages/opencode/test/plugin/github-copilot-models.test.ts:165]: Fixed. Added negative coverage for GitHub Copilot with a non-Anthropic adapter and non-Copilot Anthropic, both asserting toolStreaming is untouched.

File: packages/opencode/test/tool/read.test.ts (hunk 19 above)
Comment (Astro-Han) [reply packages/opencode/test/tool/read.test.ts]: Fixed. The TIFF fixture is now padded beyond the 4-byte signature.

File: packages/opencode/test/plugin/workspace-adaptor.test.ts (hunk 20 above)
Comment (Astro-Han) [reply packages/opencode/test/plugin/workspace-adaptor.test.ts:148]: Fixed. Replaced the broad Object.values assertion with explicit absence checks for unset OTEL env keys.

File: packages/opencode/src/tool/read.ts (hunk 21 above)
Comment (Astro-Han) [reply packages/opencode/src/tool/read.ts:160]: Fixed. Extension-based and content-inspection binary rejections now produce distinct messages, with test coverage for both paths.

File: packages/opencode/src/tool/read.ts (hunk 22 above)
Comment (Astro-Han) [reply packages/opencode/src/tool/read.ts:166]: Fixed. Sniffed media attachments now have a 5 MB cap before eager base64 encoding, with coverage for oversized renamed attachments.

File: packages/opencode/src/tool/read.ts (hunk 23 above)
Comment (Astro-Han) [reply packages/opencode/src/tool/read.ts:309]: Fixed. Added a coupling comment on the .bin/.dat sniff override so future changes keep it aligned with extension-based binary detection.

File: packages/opencode/test/plugin/workspace-adaptor.test.ts [hunk 24]
```diff
@@ -141,13 +141,22 @@ describe("plugin.workspace", () => {
...
       directory: tmp.extra.space,
       extra: { key: "value" },
     })
+    expect(created.env.OPENCODE_WORKSPACE_ID).toBe(info.id)
+    expect(created.env.OPENCODE_EXPERIMENTAL_WORKSPACES).toBe("true")
+    expect(created.env).not.toHaveProperty("OTEL_EXPORTER_OTLP_HEADERS")
+    expect(created.env).not.toHaveProperty("OTEL_EXPORTER_OTLP_ENDPOINT")
+    expect(created.env).not.toHaveProperty("OTEL_RESOURCE_ATTRIBUTES")
```
[the remark this answers is not in the document]
Comment (Astro-Han) [reply packages/opencode/test/plugin/workspace-adaptor.test.ts]: Fixed. The OTEL assertions now compare against the current process.env value for each forwarded key, so the test passes whether the runner exports OTEL variables or leaves them unset.

**Comment by Astro-Han** [comment]
Handled the CodeRabbit outside-diff review body items from the latest review:

- Fixed the session review renderability gate. Media diffs now count as renderable, expand-all only opens renderable files, and controlled open state cannot mount content for metadata-only rows.
- Left the repeated OPENCODE_AUTH_CONTENT scoping item out of #155 by design. That needs a plugin contract change, and is tracked in #173.

File: packages/opencode/src/control-plane/workspace.ts [hunk 25]
```diff
@@ -200,7 +204,17 @@ export namespace Workspace {
...
+        OPENCODE_WORKSPACE_ID: config.id,
+        OPENCODE_EXPERIMENTAL_WORKSPACES: "true",
```
[the remark this answers is not in the document]
Comment (Astro-Han) [reply packages/opencode/src/control-plane/workspace.ts:211]: Fixed. OPENCODE_WORKSPACE_ID now comes from the persisted workspace record via info.id rather than the mutable configure result.

File: packages/opencode/test/plugin/github-copilot-models.test.ts [hunk 26]
```diff
@@ -161,3 +161,72 @@ test("remaps fallback oauth model urls to the enterprise host", async () => {
...
+        id: "claude",
+        api: { id: "claude-sonnet-4.5", npm: "@ai-sdk/anthropic" },
+      },
+    } as never,
+    anthropic as never,
+  )
+
+  expect(copilotOpenAI.options).not.toHaveProperty("toolStreaming")
+  expect(anthropic.options).not.toHaveProperty("toolStreaming")
+})
```
[the remark this answers is not in the document]
Comment (Astro-Han) [reply packages/opencode/test/plugin/github-copilot-models.test.ts:232]: Fixed. Added chat.headers coverage for Copilot Anthropic setting anthropic-beta, plus negative checks for Copilot OpenAI and non-Copilot Anthropic.

File: packages/ui/src/components/session-review.tsx [hunk 27]
```diff
@@ -261,8 +263,14 @@ export const SessionReview = (props: SessionReviewProps) => {
...
+  const renderableFiles = createMemo(() =>
+    items()
+      .filter(canRenderDiff)
+      .map((diff) => diff.file),
+  )
+
   const handleExpandOrCollapseAll = () => {
-    const next = open().length > 0 ? [] : files()
+    const next = open().length > 0 ? [] : renderableFiles()
     handleChange(next)
```
[the remark this answers is not in the document]
Comment (Astro-Han) [reply packages/ui/src/components/session-review.tsx:276]: Fixed. The bulk toggle and label now use hasOpenRenderableFiles(), so non-renderable open entries do not force the button into collapse-all mode.

**Comment by Astro-Han** [comment]
@coderabbitai review

**Comment by Astro-Han** [comment]
@coderabbitai review
